export type Activity={id:number;business_key:string;activity_type:string;details?:string;outcome?:string;actor_email?:string;created_at:string;lat?:number;lon?:number}
export type Objection={id:number;business_key:string;code:string;label:string;details?:string;actor_email?:string;created_at:string}
export type Followup={id:number;business_key:string;business_name?:string;title:string;due_at:string;status:string;source?:string;notes?:string;completed_at?:string}
export type Pain={code:string;label:string;severity:'high'|'medium'|'low'|'info';evidence:string}
export type NextBestAction={action:string;label:string;reason:string;priority:number;due_at?:string}
export type FieldEvidence={field:string;label:string;value:any;source:string;confidence:number;status:'known'|'unknown'|'not_found'|'inferred'|string}
export type Lead={
 business_key:string;name:string;address?:string;lat:number;lon:number;category?:string;phone?:string;website?:string;rating?:number;reviews?:number;
 opportunity_score?:number;commercial_potential_score?:number;conversion_probability?:number;visit_priority_score?:number;digital_maturity_score?:number;ai_search_readiness_score?:number;
 target_fit_score?:number;target_fit_reason?:string;is_large_chain?:boolean;site_functional?:boolean;has_booking?:boolean;has_catalog?:boolean;has_whatsapp?:boolean;
 has_instagram?:boolean;manual_booking_detected?:boolean;manual_booking_evidence?:string;booking_provider?:string;competitor_detected?:boolean;competitor_name?:string;pipeline_status?:string;visited?:boolean;
 score_reasons?:string[];why_approach?:string;sales_pitch?:string;assigned_to?:string;contact_name?:string;contact_phone?:string;next_action_at?:string;
 notes?:string;lost_reason?:string;do_not_contact?:boolean;estimated_mrr?:number;presence_completeness_score?:number;has_structured_data?:boolean;
 has_local_business_schema?:boolean;robots_noindex?:boolean;provider?:string;data_confidence?:number;campaign_name?:string;score_profile?:string;
 city_name?:string;state_name?:string;district_name?:string;pitch_variant?:string;likely_objection?:string;last_objection_code?:string;last_objection_note?:string;
 ai_provider_used?:string;ai_model_used?:string;activities?:Activity[];objections?:Objection[];followups?:Followup[];open_now?:boolean;opening_hours_text?:string;
 decision_maker_name?:string;decision_maker_role?:string;decision_maker_confidence?:number;company_size_estimate?:string;last_contact_at?:string;first_seen_at?:string;last_analyzed_at?:string;last_seen_at?:string;
 next_reanalysis_at?:string;last_reanalysis_at?:string;pains?:Pain[];next_best_action?:NextBestAction;field_evidence?:FieldEvidence[];aging_days?:number;aging_label?:string;reputation_insight?:string;
 identity_key?:string;source_keys?:string[];digital_gap_score?:number;commercial_fit_score?:number;conversion_confidence?:number;expected_mrr_value?:number;product_fit?:Record<string,number>;tags?:string[];change_summary?:any[];changes?:LeadChange[];intelligence?:LeadIntelligence;competitor_playbook?:LeadIntelligence['competitor_playbook'];duplicates?:{lead:Lead;reasons:string[]}[];cadences?:any[]
}
export type SearchJob={id:number;query_text:string;center_lat:number;center_lon:number;center_display_name?:string;radius_m:number;provider:string;status:string;stage:string;total_items:number;processed_items:number;failed_items:number;new_items:number;reused_items:number;config?:Record<string,any>;results?:Lead[];source_counts?:Record<string,number>;raw_discovered_count?:number;deduplicated_count?:number;incremental_from_job_id?:number;estimated_cost_usd?:number;snapshot_locked?:boolean}
export type MetricSet={total:number;website_pct:number;functional_site_pct:number;booking_pct:number;manual_booking_pct:number;catalog_pct:number;whatsapp_pct:number;instagram_pct:number;structured_data_pct:number;local_business_schema_pct?:number;online_presence_avg?:number;digital_maturity_avg?:number;ai_readiness_avg?:number;rating_avg?:number;reviews_avg?:number;[key:string]:any}
export type Report={lead:Lead;context:{job_id:number;query_text?:string;radius_m?:number;center_display_name?:string;sample_size:number;segment:string;segment_sample_size:number;city_name?:string;district_name?:string};area_metrics:MetricSet;segment_metrics:MetricSet;city_metrics:MetricSet;city_segment_metrics:MetricSet;district_metrics:MetricSet;district_segment_metrics:MetricSet;comparisons:{key:string;label:string;sample_size:number;metrics:MetricSet}[];benchmark:{digital_maturity_rank:number;sample_size:number;percentile:number};city_benchmark:{digital_maturity_rank:number;sample_size:number;percentile:number};segment_benchmark:{digital_maturity_rank:number;sample_size:number;percentile:number};gaps:{severity:string;title:string;detail:string}[];ai_search_alert?:{level:string;title:string;message:string;sources:{title:string;url:string}[]};disclaimer:string;public?:{token:string;expires_at?:string};evolution?:{baseline?:Record<string,any>|null;current?:Record<string,any>;changes?:{field:string;before:any;after:any}[]};solution_map?:Record<string,string>}
export type AdvancedDashboard={summary:Record<string,number>;leaderboard?:{member:string;activities:number;visits:number;clients:number;conversion_pct:number}[];funnel:Record<string,number>;campaigns:{name:string;leads:number;clients:number;mrr:number}[];providers:{name:string;leads:number;clients:number}[];objections:{code:string;label:string;count:number}[];losses:{reason:string;count:number}[];pitch_ab:{variant:string;leads:number;positives:number;clients:number}[];converting:{profile:string;leads:number;clients:number;avg_client_opportunity?:number}[];converting_signals:{signal:string;leads:number;clients:number;conversion_pct:number}[];ai_usage:{calls:number;input_tokens:number;output_tokens:number;cost_usd:number;errors:number}}
export type AppSettings={default_mrr:number;default_score_profile:string;default_ai_provider:string;ai_min_score:number;ai_daily_call_limit:number;ai_daily_budget_usd:number;ai_limit_per_batch:number;gemini_model:string;openrouter_model:string;openai_model:string;route_mode:string;route_available_minutes:number;route_visit_minutes:number;route_max_stops:number;available_ai?:Record<string,boolean>;ai_usage_today?:Record<string,number>}
export type RouteScheduleStop={business_key:string;name:string;arrival?:string;departure?:string;travel_minutes:number;visit_minutes:number;expected_mrr_value:number;conversion_probability?:number;visit_priority_score?:number;fixed?:boolean;why_approach?:string;open_now?:boolean;open_at_arrival?:boolean;opening_hours_text?:string;hours_warning?:string;lead_notes?:string;assigned_to?:string;campaign_name?:string}
export type RoutePlan={ordered:Lead[];schedule:RouteScheduleStop[];omitted?:{business_key:string;name?:string;reason:string}[];matrix_engine?:string;used_minutes:number;geometry?:{line:number[][];distance_m?:number;duration_s?:number;provider?:string};distance_m?:number;duration_s?:number;strategy?:string;exceeds_window?:boolean;saved_route?:SavedRoute}
export type RouteStop={id:number;route_id:number;business_key:string;position:number;status:string;fixed:boolean;removal_reason?:string;notes?:string;travel_minutes?:number;arrival_at?:string;departure_at?:string;expected_mrr_value?:number;name:string;address?:string;lat:number;lon:number;visit_priority_score?:number;pipeline_status?:string;why_approach?:string;estimated_mrr?:number;conversion_probability?:number;open_now?:boolean;lead_notes?:string;assigned_to?:string;campaign_name?:string}
export type SavedRoute={id:number;name:string;route_date?:string;status:string;owner_email?:string;campaign_name?:string;strategy:string;mode:string;origin_lat:number;origin_lon:number;origin_label?:string;end_lat?:number;end_lon?:number;end_label?:string;available_minutes:number;visit_minutes:number;max_stops:number;geometry?:any;summary?:any;stops?:RouteStop[]}
export type TodayWorkspace={date:string;due_followups:Followup[];next_actions:{lead:Lead;action:NextBestAction}[];goals:any[];routes:SavedRoute[]}
export type Territory={id:number;name:string;city_name?:string;district_name?:string;assigned_to?:string;center_lat?:number;center_lon?:number;radius_m?:number;polygon?:any;active:boolean}
export type ICP={id:number;name:string;config:Record<string,any>;active:boolean}
export type ProviderHealth={database:string;geoapify:{configured:boolean};foursquare:{configured:boolean};ai:Record<string,{configured:boolean;model?:string}>;routing:Record<string,any>;jobs:Record<string,number>;ai_usage_today:Record<string,number>}
export type LeadIntelligence={digital_gap_score:number;commercial_fit_score:number;conversion_probability:number;conversion_confidence:number;expected_mrr_value:number;product_fit:{agenda:number;assinatura:number;crediario:number;digital_gap:number};decision_reasons:string[];counterfactual?:string[];competitor_playbook:{competitor:string;angle:string;questions:string[]}}
export type LeadChange={id:number;business_key:string;field_name:string;old_value?:string;new_value?:string;change_type:string;created_at:string}
export type IntelligenceOverview={totals:{leads:number;clients:number;expected_mrr:number};segments:{name:string;leads:number;clients:number;conversion_pct:number;expected_mrr:number}[];pitches:{variant:string;leads:number;positive:number;clients:number;positive_pct:number;client_pct:number;client_ci_low?:number;client_ci_high?:number;confidence_label?:string}[];suggested_icp?:{segment:string;observed_conversion_pct:number;sample_size:number;signals:Record<string,number>;confidence:string}|null;signals:{signal:string;leads:number;clients:number;conversion_pct:number}[];recommended:{lead:Lead;intelligence:LeadIntelligence;decision_score:number}[];insights:string[]}
export type CadenceTemplate={id:number;name:string;description?:string;steps:{delay_days:number;action?:string;title?:string;notes?:string}[];active:boolean}
export type AutomationRule={id:number;name:string;event_name:string;conditions:Record<string,any>;actions:Record<string,any>[];active:boolean;created_at:string}
export type WebhookSubscription={id:number;name:string;url:string;events:string[];active:boolean;created_at:string}
export type ImportBatch={id:number;filename?:string;imported_by?:string;total_rows:number;imported_rows:number;duplicate_rows:number;error_rows:number;created_at:string}
