import {useMemo,useState} from 'react'
import type {Report} from '@/types'
import {Card} from '@/components/ui/Card'
import {Badge} from '@/components/ui/Badge'
import {AlertTriangle,CheckCircle2,Globe2,Printer,Share2,TrendingUp} from 'lucide-react'
import {Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {Button} from '@/components/ui/Button'

const pct=(v:any)=>`${Number(v||0).toFixed(0)}%`
const metrics=[['website_pct','Site'],['functional_site_pct','Site funcional'],['booking_pct','Agenda online'],['catalog_pct','Catálogo/serviços'],['whatsapp_pct','WhatsApp'],['structured_data_pct','Dados estruturados']]
export function BusinessReportView({r,publicMode=false,onShare}:{r:Report;publicMode?:boolean;onShare?:()=>void}){
 const[ticket,setTicket]=useState(80),[lost,setLost]=useState(8),[conversion,setConversion]=useState(35)
 const opportunity=useMemo(()=>ticket*lost,[ticket,lost]);const recovered=useMemo(()=>opportunity*conversion/100,[opportunity,conversion])
 const chart=metrics.slice(0,5).map(([k,name])=>({name,raio:(r.area_metrics as any)[k]||0,segmento:(r.segment_metrics as any)[k]||0,cidade:(r.city_metrics as any)[k]||0,cidadeSegmento:(r.city_segment_metrics as any)[k]||0}))
 const l=r.lead
 return <div className="space-y-6 print:bg-white">
  <div className="no-print flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={()=>window.print()}><Printer className="h-4 w-4"/>Imprimir / salvar PDF</Button>{!publicMode&&onShare&&<Button onClick={onShare}><Share2 className="h-4 w-4"/>Criar link para o estabelecimento</Button>}</div>
  <section className="rounded-2xl border border-border bg-surface p-6 print-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">BeeSys · diagnóstico comparativo</p><h1 className="mt-2 text-3xl font-bold">{l.name}</h1><p className="mt-1 text-sm text-muted">{l.address}</p><p className="mt-2 text-sm text-muted">Segmento: {r.context.segment} · Amostra do raio: {r.context.sample_size} negócios</p></div><div className="grid grid-cols-2 gap-2"><div className="rounded-xl bg-primary-soft p-4 text-center"><p className="text-xs text-primary">Maturidade digital</p><p className="mt-1 text-3xl font-bold text-primary">{l.digital_maturity_score||0}</p></div><div className="rounded-xl bg-background p-4 text-center"><p className="text-xs text-muted">Posição no raio</p><p className="mt-1 text-2xl font-bold">{r.benchmark.digital_maturity_rank}º</p><p className="text-xs text-muted">de {r.benchmark.sample_size}</p></div></div></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border p-4"><p className="text-xs text-muted">À frente de</p><p className="mt-1 text-2xl font-bold">{pct(r.benchmark.percentile)}</p><p className="text-xs text-muted">dos negócios no raio</p></div><div className="rounded-xl border border-border p-4"><p className="text-xs text-muted">Posição na cidade</p><p className="mt-1 text-2xl font-bold">{r.city_benchmark.digital_maturity_rank}º</p><p className="text-xs text-muted">em {r.city_benchmark.sample_size} analisados</p></div><div className="rounded-xl border border-border p-4"><p className="text-xs text-muted">Mesmo segmento no raio</p><p className="mt-1 text-2xl font-bold">{r.segment_benchmark.digital_maturity_rank}º</p><p className="text-xs text-muted">em {r.segment_benchmark.sample_size} semelhantes</p></div></div></section>
  {r.ai_search_alert&&<section className="rounded-2xl border border-red-200 bg-danger-soft p-5 print-card"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-danger"/><div><h2 className="font-semibold text-danger">{r.ai_search_alert.title}</h2><p className="mt-2 text-sm leading-6 text-red-900">{r.ai_search_alert.message}</p><p className="mt-2 text-xs text-red-800">Este alerta não significa que a empresa deixará de aparecer no Google. Ele indica menor controle sobre conteúdo próprio rastreável e indexável, num cenário em que AI Overviews e AI Mode usam conteúdo do índice da Pesquisa.</p><div className="mt-3 flex flex-wrap gap-3 no-print">{r.ai_search_alert.sources.map(x=><a key={x.url} className="text-xs font-semibold text-danger underline" target="_blank" rel="noreferrer" href={x.url}>{x.title}</a>)}</div></div></div></section>}
  <Card className="print-card"><h2 className="font-semibold">Como o estabelecimento se compara</h2><p className="mt-1 text-sm text-muted">Os percentuais representam a amostra realmente encontrada pelas fontes configuradas. “Não identificado” não é tratado como certeza absoluta de ausência.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-border text-muted"><tr><th className="pb-3">Grupo comparado</th>{metrics.map(([,n])=><th key={n} className="pb-3">{n}</th>)}</tr></thead><tbody>{r.comparisons.map(c=><tr key={c.key} className="border-b border-border last:border-0"><td className="py-3 pr-4"><b>{c.label}</b><p className="text-xs text-muted">{c.sample_size} negócios</p></td>{metrics.map(([k])=><td key={k} className="py-3">{pct((c.metrics as any)[k])}</td>)}</tr>)}</tbody></table></div></Card>
  <div className="grid gap-5 lg:grid-cols-2"><Card className="print-card"><h2 className="font-semibold">Raio, segmento e cidade</h2><div className="mt-5 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Legend/><Bar dataKey="raio" name="Raio" fill="#4338ca" radius={[4,4,0,0]}/><Bar dataKey="segmento" name="Mesmo segmento no raio" fill="#e8a91b" radius={[4,4,0,0]}/><Bar dataKey="cidadeSegmento" name="Mesmo segmento na cidade" fill="#16a34a" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card className="print-card"><h2 className="font-semibold">Onde existe espaço para evoluir</h2><div className="mt-4 space-y-3">{r.gaps.length?r.gaps.map(g=><div key={g.title} className="rounded-xl border border-border p-4"><div className="flex items-center gap-2"><Badge tone={g.severity==='high'?'danger':g.severity==='medium'?'warning':'neutral'}>{g.severity==='high'?'Prioridade alta':g.severity==='medium'?'Atenção':'Oportunidade'}</Badge><b className="text-sm">{g.title}</b></div><p className="mt-2 text-sm leading-6 text-muted">{g.detail}</p></div>):<div className="flex gap-3 rounded-xl bg-success-soft p-4"><CheckCircle2 className="h-5 w-5 text-success"/><p className="text-sm text-success">O estabelecimento já apresenta boa cobertura nos principais sinais analisados.</p></div>}</div></Card></div>
  <div className="grid gap-4 md:grid-cols-3"><Card className="print-card"><p className="text-sm text-muted">Este negócio</p><p className="mt-2 text-3xl font-bold">{l.website?'Site identificado':'Site não identificado'}</p><p className="mt-2 text-sm text-muted">Na região, {pct(r.area_metrics.website_pct)} possuem site identificado.</p></Card><Card className="print-card"><p className="text-sm text-muted">Agendamento</p><p className="mt-2 text-3xl font-bold">{l.has_booking?'Online':l.manual_booking_detected?'Manual':'Não identificado'}</p><p className="mt-2 text-sm text-muted">No mesmo segmento no raio, {pct(r.segment_metrics.booking_pct)} já têm agendamento online identificado.</p></Card><Card className="print-card"><p className="text-sm text-muted">Prontidão para busca com IA</p><p className="mt-2 text-3xl font-bold">{l.ai_search_readiness_score||0}/100</p><p className="mt-2 text-sm text-muted">Indicador BeeSys; não é métrica oficial do Google.</p></Card></div>
  <Card className="print-card"><div className="flex items-start gap-3"><TrendingUp className="mt-0.5 h-5 w-5 text-primary"/><div className="flex-1"><h2 className="font-semibold">Simulador de oportunidade</h2><p className="mt-1 text-sm text-muted">Use números do próprio estabelecimento. O cálculo é um cenário, não uma promessa de resultado.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm">Ticket médio (R$)<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={ticket} onChange={e=>setTicket(Number(e.target.value))}/></label><label className="text-sm">Oportunidades perdidas/mês<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={lost} onChange={e=>setLost(Number(e.target.value))}/></label><label className="text-sm">Recuperação estimada (%)<input type="number" min="0" max="100" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={conversion} onChange={e=>setConversion(Number(e.target.value))}/></label></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-background p-4"><p className="text-xs text-muted">Receita associada às oportunidades informadas</p><p className="mt-1 text-2xl font-bold">R$ {opportunity.toLocaleString('pt-BR',{minimumFractionDigits:2})}</p></div><div className="rounded-xl bg-primary-soft p-4"><p className="text-xs text-primary">Cenário de receita recuperada</p><p className="mt-1 text-2xl font-bold text-primary">R$ {recovered.toLocaleString('pt-BR',{minimumFractionDigits:2})}/mês</p></div></div></div></div></Card>
  <Card className="print-card"><h2 className="font-semibold">Cenário de evolução com digitalização</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[['Agenda',l.has_booking?'Já possui':'Organizar horários online'],['Lembretes','Automatizar confirmações e retornos'],['Serviços',l.has_catalog?'Já apresenta':'Apresentar catálogo/serviços'],['Presença digital',l.website?'Melhorar estrutura e indexabilidade':'Criar presença própria rastreável']].map(([a,b])=><div key={a} className="rounded-xl border border-border p-4"><p className="text-xs font-semibold uppercase text-muted">{a}</p><p className="mt-2 text-sm font-medium">{b}</p></div>)}</div></Card>
  <Card className="print-card"><div className="flex items-start gap-3"><Globe2 className="mt-0.5 h-5 w-5 text-primary"/><div><h2 className="font-semibold">Como interpretar este relatório</h2><p className="mt-2 text-sm leading-6 text-muted">{r.disclaimer} A comparação serve para mostrar posição digital relativa e oportunidades práticas. Os dados podem variar conforme cobertura das fontes, data da coleta e disponibilidade pública das informações.</p></div></div></Card>
 </div>
}
