import {useRef,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Database,Upload,Shield,Activity,FileSpreadsheet,UserCog,LockKeyhole} from 'lucide-react'
import {api} from '@/services/api'
import type {ImportBatch} from '@/types'
import {Card} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import {Badge} from '@/components/ui/Badge'

const parseCsv=(text:string)=>{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const sep=(lines[0].match(/;/g)||[]).length>(lines[0].match(/,/g)||[]).length?';':',';const split=(line:string)=>{const out:string[]=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===sep&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out};const headers=split(lines[0]).map(x=>x.trim().toLowerCase());return lines.slice(1).slice(0,5000).map(line=>Object.fromEntries(headers.map((h,i)=>[h,split(line)[i]??''])))}
const fileToBase64=async(file:File)=>{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(binary)}


export function AdminPage(){
 const qc=useQueryClient(),fileRef=useRef<HTMLInputElement>(null)
 const overview=useQuery({queryKey:['admin-overview'],queryFn:()=>api.get<any>('/api/admin/overview')})
 const imports=useQuery({queryKey:['imports'],queryFn:()=>api.get<ImportBatch[]>('/api/imports')})
 const[roleEmail,setRoleEmail]=useState(''),[role,setRole]=useState('SELLER'),[importMsg,setImportMsg]=useState('')
 const saveRole=useMutation({mutationFn:()=>api.post('/api/admin/roles',{email:roleEmail,role}),onSuccess:()=>{setRoleEmail('');qc.invalidateQueries({queryKey:['admin-overview']})}})
 const importMutation=useMutation({mutationFn:async(file:File)=>{if(file.size>12*1024*1024)throw new Error('Arquivo maior que 12 MB');if(file.name.toLowerCase().endsWith('.csv')){const rows=parseCsv(await file.text());if(!rows.length)throw new Error('CSV vazio');return api.post<any>('/api/import/leads',{filename:file.name,rows})}return api.post<any>('/api/import/file',{filename:file.name,content_base64:await fileToBase64(file)})},onSuccess:d=>{setImportMsg(`${d.imported} importados · ${d.duplicates} duplicados · ${d.errors.length} erros`);qc.invalidateQueries({queryKey:['imports']});qc.invalidateQueries({queryKey:['admin-overview']})}})
 const privacyComplete=useMutation({mutationFn:({id,anonymize}:{id:number;anonymize:boolean})=>api.post(`/api/privacy/requests/${id}/complete`,{anonymize}),onSuccess:()=>qc.invalidateQueries({queryKey:['admin-overview']})})
 const d=overview.data||{}
 return <div className="space-y-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Governança e operação</p><h1 className="mt-1 text-3xl font-bold">Administração</h1><p className="mt-1 max-w-3xl text-sm text-muted">Observabilidade, importações, papéis, auditoria e solicitações de privacidade em um único lugar.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><Database className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted">Fontes monitoradas</p><b className="text-2xl">{(d.providers||[]).length}</b></Card><Card><Activity className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted">Chamadas IA hoje</p><b className="text-2xl">{d.ai?.calls||0}</b></Card><Card><Upload className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted">Importações recentes</p><b className="text-2xl">{(d.imports||[]).length}</b></Card><Card><LockKeyhole className="h-5 w-5 text-primary"/><p className="mt-3 text-xs text-muted">Pedidos de privacidade</p><b className="text-2xl">{(d.privacy||[]).filter((x:any)=>x.status==='OPEN').length}</b></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><div className="flex items-center gap-2"><FileSpreadsheet className="h-5 w-5 text-primary"/><h2 className="font-semibold">Importar base CSV ou XLSX</h2></div><p className="mt-1 text-sm text-muted">Aceita CSV e XLSX com nome, latitude/lat, longitude/lon e opcionalmente telefone, site, categoria, endereço, campanha e MRR. A importação passa pela mesma identidade e deduplicação.</p><input ref={fileRef} type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)importMutation.mutate(f)}}/><Button className="mt-4" onClick={()=>fileRef.current?.click()} disabled={importMutation.isPending}><Upload className="h-4 w-4"/>{importMutation.isPending?'Importando...':'Selecionar CSV/XLSX'}</Button>{importMsg&&<p className="mt-3 rounded-xl bg-success-soft p-3 text-sm text-success">{importMsg}</p>}{importMutation.error&&<p className="mt-3 text-sm text-danger">{(importMutation.error as Error).message}</p>}<div className="mt-4 space-y-2">{(imports.data||[]).slice(0,6).map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border border-border p-3 text-sm"><div><b>{x.filename}</b><p className="text-xs text-muted">{new Date(x.created_at).toLocaleString('pt-BR')}</p></div><span className="text-xs text-muted">{x.imported_rows}/{x.total_rows} importados</span></div>)}</div></Card>
   <Card><div className="flex items-center gap-2"><UserCog className="h-5 w-5 text-primary"/><h2 className="font-semibold">Papéis da equipe</h2></div><p className="mt-1 text-sm text-muted">Estrutura pronta para Admin, Gestor, Vendedor e Visualizador. O primeiro usuário continua funcional mesmo antes de cadastrar papéis.</p><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_160px_auto]"><input className="h-11 rounded-xl border border-border px-3" placeholder="email@empresa.com" value={roleEmail} onChange={e=>setRoleEmail(e.target.value)}/><select className="h-11 rounded-xl border border-border bg-surface px-3" value={role} onChange={e=>setRole(e.target.value)}><option>ADMIN</option><option>MANAGER</option><option>SELLER</option><option>VIEWER</option></select><Button disabled={!roleEmail||saveRole.isPending} onClick={()=>saveRole.mutate()}>Salvar</Button></div><div className="mt-4 space-y-2">{(d.roles||[]).map((x:any)=><div key={x.email} className="flex items-center justify-between rounded-xl border border-border p-3"><span className="text-sm">{x.email}</span><Badge tone={x.role==='ADMIN'?'primary':'neutral'}>{x.role}</Badge></div>)}</div></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><div className="flex items-center gap-2"><Activity className="h-5 w-5 text-primary"/><h2 className="font-semibold">Consumo dos provedores</h2></div><div className="mt-4 space-y-2">{(d.providers||[]).map((x:any)=><div key={`${x.provider}-${x.operation}`} className="rounded-xl border border-border p-3"><div className="flex justify-between"><b className="text-sm">{x.provider}</b><span className="text-xs text-primary">{x.calls} chamadas</span></div><p className="mt-1 text-xs text-muted">{x.operation} · {x.results} resultados</p></div>)}</div></Card><Card><div className="flex items-center gap-2"><Shield className="h-5 w-5 text-primary"/><h2 className="font-semibold">Auditoria recente</h2></div><div className="mt-4 max-h-96 space-y-2 overflow-auto">{(d.audits||[]).map((x:any)=><div key={x.id} className="rounded-xl border border-border p-3 text-xs"><div className="flex justify-between gap-2"><b>{x.action}</b><span className="text-muted">{new Date(x.created_at).toLocaleString('pt-BR')}</span></div><p className="mt-1 text-muted">{x.actor_email||'sistema'} · {x.entity_type} {x.entity_id||''}</p></div>)}</div></Card></div>
  <Card><div className="flex items-center gap-2"><LockKeyhole className="h-5 w-5 text-primary"/><h2 className="font-semibold">Solicitações de privacidade</h2></div><p className="mt-1 text-sm text-muted">Revise pedidos de remoção/anonimização. A anonimização limpa contatos e notas pessoais do lead e marca “não contatar”.</p><div className="mt-4 space-y-2">{(d.privacy||[]).slice(0,20).map((x:any)=><div key={x.id} className="rounded-xl border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><b className="text-sm">#{x.id} · {x.request_type}</b><p className="text-xs text-muted">{x.business_key||x.contact_value||'Sem lead vinculado'} · {x.status}</p></div>{x.status==='OPEN'&&<div className="flex gap-2"><Button variant="secondary" disabled={privacyComplete.isPending} onClick={()=>privacyComplete.mutate({id:x.id,anonymize:false})}>Concluir</Button>{x.business_key&&<Button variant="secondary" disabled={privacyComplete.isPending} onClick={()=>{if(confirm('Anonimizar contatos e notas pessoais deste lead?'))privacyComplete.mutate({id:x.id,anonymize:true})}}>Anonimizar</Button>}</div>}</div>{x.details&&<p className="mt-2 text-xs text-muted">{x.details}</p>}</div>)}{!(d.privacy||[]).length&&<p className="text-sm text-muted">Nenhuma solicitação registrada.</p>}</div></Card>
 </div>
}
