import {useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {Workflow,Webhook,Clock3,Plus,Power,ShieldCheck} from 'lucide-react'
import {api} from '@/services/api'
import type {AutomationRule,CadenceTemplate,WebhookSubscription} from '@/types'
import {Card} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import {Badge} from '@/components/ui/Badge'

export function AutomationsPage(){
 const qc=useQueryClient()
 const cadences=useQuery({queryKey:['cadences'],queryFn:()=>api.get<CadenceTemplate[]>('/api/cadences')})
 const rules=useQuery({queryKey:['automations'],queryFn:()=>api.get<AutomationRule[]>('/api/automations')})
 const webhooks=useQuery({queryKey:['webhooks'],queryFn:()=>api.get<WebhookSubscription[]>('/api/webhooks')})
 const[cName,setCName]=useState('Cadência presencial padrão'),[cDesc,setCDesc]=useState('Visita, WhatsApp e retorno comercial')
 const[rName,setRName]=useState('Lead quente → follow-up'),[rScore,setRScore]=useState(85),[rDays,setRDays]=useState(1)
 const[wName,setWName]=useState('n8n / CRM'),[wUrl,setWUrl]=useState(''),[wEvents,setWEvents]=useState('lead.client,lead.updated')
 const createCadence=useMutation({mutationFn:()=>api.post('/api/cadences',{name:cName,description:cDesc,steps:[{delay_days:0,title:'Primeiro contato',action:'VISIT'},{delay_days:2,title:'WhatsApp pós-visita',action:'WHATSAPP'},{delay_days:7,title:'Follow-up comercial',action:'FOLLOW_UP'},{delay_days:21,title:'Reativação',action:'REACTIVATE'}]}),onSuccess:()=>qc.invalidateQueries({queryKey:['cadences']})})
 const createRule=useMutation({mutationFn:()=>api.post('/api/automations',{name:rName,event_name:'lead.updated',conditions:{min_score:rScore},actions:[{type:'followup',days:rDays,title:'Follow-up automático de lead quente'}],active:true}),onSuccess:()=>qc.invalidateQueries({queryKey:['automations']})})
 const toggle=useMutation({mutationFn:({id,active}:{id:number;active:boolean})=>api.patch(`/api/automations/${id}`,{active}),onSuccess:()=>qc.invalidateQueries({queryKey:['automations']})})
 const createWebhook=useMutation({mutationFn:()=>api.post('/api/webhooks',{name:wName,url:wUrl,events:wEvents.split(',').map(x=>x.trim()).filter(Boolean)}),onSuccess:()=>{setWUrl('');qc.invalidateQueries({queryKey:['webhooks']})}})
 return <div className="space-y-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Operação escalável</p><h1 className="mt-1 text-3xl font-bold">Automações</h1><p className="mt-1 max-w-3xl text-sm text-muted">Padronize cadências, próximos passos e integrações. As regras ficam explícitas e auditáveis.</p></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><div className="flex items-center gap-2"><Clock3 className="h-5 w-5 text-primary"/><h2 className="font-semibold">Cadências comerciais</h2></div><p className="mt-1 text-sm text-muted">Crie uma sequência reutilizável de visitas e follow-ups.</p><div className="mt-4 grid gap-2"><input className="h-11 rounded-xl border border-border px-3" value={cName} onChange={e=>setCName(e.target.value)}/><input className="h-11 rounded-xl border border-border px-3" value={cDesc} onChange={e=>setCDesc(e.target.value)}/><Button onClick={()=>createCadence.mutate()} disabled={createCadence.isPending}><Plus className="h-4 w-4"/>Salvar cadência padrão</Button></div><div className="mt-5 space-y-2">{(cadences.data||[]).map(c=><div key={c.id} className="rounded-xl border border-border p-3"><div className="flex items-center justify-between"><b className="text-sm">{c.name}</b><Badge tone={c.active?'success':'neutral'}>{c.active?'Ativa':'Inativa'}</Badge></div><p className="mt-1 text-xs text-muted">{c.description}</p><div className="mt-2 flex flex-wrap gap-1">{c.steps.map((s,i)=><span key={i} className="rounded-md bg-background px-2 py-1 text-[11px]">D+{s.delay_days} · {s.title||s.action}</span>)}</div></div>)}</div></Card>
   <Card><div className="flex items-center gap-2"><Workflow className="h-5 w-5 text-primary"/><h2 className="font-semibold">Regras automáticas</h2></div><p className="mt-1 text-sm text-muted">Exemplo: lead com prioridade alta recebe follow-up automaticamente.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input className="h-11 rounded-xl border border-border px-3 sm:col-span-2" value={rName} onChange={e=>setRName(e.target.value)}/><label className="text-sm">Score mínimo<input type="number" className="mt-1 h-11 w-full rounded-xl border border-border px-3" value={rScore} onChange={e=>setRScore(Number(e.target.value))}/></label><label className="text-sm">Follow-up em dias<input type="number" className="mt-1 h-11 w-full rounded-xl border border-border px-3" value={rDays} onChange={e=>setRDays(Number(e.target.value))}/></label></div><Button className="mt-3" onClick={()=>createRule.mutate()} disabled={createRule.isPending}><Plus className="h-4 w-4"/>Criar automação</Button><div className="mt-5 space-y-2">{(rules.data||[]).map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-xl border border-border p-3"><div><b className="text-sm">{r.name}</b><p className="mt-1 text-xs text-muted">Evento {r.event_name} · condições transparentes</p></div><button className={`grid h-10 w-10 place-items-center rounded-xl ${r.active?'bg-success-soft text-success':'bg-background text-muted'}`} onClick={()=>toggle.mutate({id:r.id,active:!r.active})} aria-label="Ativar/desativar"><Power className="h-4 w-4"/></button></div>)}</div></Card></div>
  <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Webhook className="h-5 w-5 text-primary"/><h2 className="font-semibold">Webhooks e n8n</h2></div><p className="mt-1 text-sm text-muted">Dispare eventos para automações externas. Somente URLs HTTPS públicas são aceitas.</p></div><div className="flex items-center gap-2 text-xs text-success"><ShieldCheck className="h-4 w-4"/>Validação contra hosts privados</div></div><div className="mt-4 grid gap-2 lg:grid-cols-[.6fr_1fr_1fr_auto]"><input className="h-11 rounded-xl border border-border px-3" value={wName} onChange={e=>setWName(e.target.value)} placeholder="Nome"/><input className="h-11 rounded-xl border border-border px-3" value={wUrl} onChange={e=>setWUrl(e.target.value)} placeholder="https://..."/><input className="h-11 rounded-xl border border-border px-3" value={wEvents} onChange={e=>setWEvents(e.target.value)} placeholder="lead.client, lead.updated"/><Button onClick={()=>createWebhook.mutate()} disabled={!wUrl||createWebhook.isPending}>Adicionar</Button></div>{createWebhook.error&&<p className="mt-2 text-sm text-danger">{(createWebhook.error as Error).message}</p>}<div className="mt-4 grid gap-2 md:grid-cols-2">{(webhooks.data||[]).map(w=><div key={w.id} className="rounded-xl border border-border p-3"><div className="flex items-center justify-between"><b className="text-sm">{w.name}</b><Badge tone={w.active?'success':'neutral'}>{w.active?'Ativo':'Inativo'}</Badge></div><p className="mt-1 truncate text-xs text-muted">{w.url}</p><p className="mt-2 text-[11px] text-muted">{w.events.join(' · ')}</p></div>)}</div></Card>
 </div>
}
