import {useQuery} from '@tanstack/react-query'
import {api} from '@/services/api'
import {Card} from '@/components/ui/Card'
import type {AdvancedDashboard} from '@/types'
import {Link} from 'react-router-dom'
import {ArrowRight,Target,TrendingUp,Users,MapPin,Clock3,WalletCards} from 'lucide-react'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {PageSkeleton} from '@/components/ui/Skeleton'

const pct=(a:number,b:number)=>b?`${(100*a/b).toFixed(1)}%`:'0%'
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})

export function DashboardPage(){
 const q=useQuery({queryKey:['dashboard-advanced'],queryFn:()=>api.get<AdvancedDashboard>('/api/dashboard/advanced')});const d=q.data
 if(!d)return <PageSkeleton/>
 const f=d.funnel||{};const funnel=[['Leads',f.LEADS||0],['Contatos',f.CONTACTS||0],['Visitas',f.VISITS||0],['Interessados',f.INTERESTED||0],['Demos',f.DEMOS||0],['Propostas',f.PROPOSALS||0],['Clientes',f.CLIENTS||0]]
 const mrr=(d.campaigns||[]).reduce((a,c)=>a+Number(c.mrr||0),0)
 const executive=[
  {label:'Leads na base',value:d.summary.total||0,icon:Users,help:`${d.summary.hot||0} com alta prioridade`},
  {label:'Visitas realizadas',value:f.VISITS||d.summary.visited||0,icon:MapPin,help:`${pct(f.INTERESTED||0,f.VISITS||0)} viraram interessados`},
  {label:'Interessados',value:f.INTERESTED||d.summary.interested||0,icon:Target,help:`${pct(f.DEMOS||0,f.INTERESTED||0)} avançaram para demo`},
  {label:'Clientes',value:f.CLIENTS||d.summary.clients||0,icon:TrendingUp,help:`${pct(f.CLIENTS||0,f.LEADS||0)} conversão total`},
  {label:'MRR conquistado',value:money(mrr),icon:WalletCards,help:'Receita recorrente dos clientes registrados'},
  {label:'IA hoje',value:d.ai_usage.calls||0,icon:Clock3,help:`US$ ${Number(d.ai_usage.cost_usd||0).toFixed(4)} estimados`},
 ]
 return <div className="space-y-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Visão executiva</p><h1 className="mt-1 text-3xl font-bold">Dashboard comercial</h1><p className="mt-1 text-sm text-muted">O que está acontecendo no funil, onde há gargalos e quais sinais estão gerando clientes.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{executive.map(x=><Card key={x.label} className="min-h-32"><div className="flex items-center justify-between"><span className="text-sm text-muted">{x.label}</span><x.icon className="h-4 w-4 text-primary"/></div><p className="metric-number mt-3 text-3xl font-bold">{x.value}</p><p className="mt-2 text-xs leading-5 text-muted">{x.help}</p></Card>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-semibold">Funil de conversão</h2><p className="mt-1 text-sm text-muted">Da descoberta do negócio até cliente.</p></div><span className="text-sm font-semibold text-primary">{pct(f.CLIENTS||0,f.LEADS||0)} conversão final</span></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel.map(([stage,value])=>({stage,value}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="stage"/><YAxis/><Tooltip/><Bar dataKey="value" name="Quantidade" fill="#4338ca" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></Card>
   <Card><h2 className="font-semibold">Onde agir agora</h2><div className="mt-4 space-y-4"><div><div className="flex justify-between text-sm"><span>Visita → interessado</span><b>{pct(f.INTERESTED||0,f.VISITS||0)}</b></div><div className="mt-2 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:pct(f.INTERESTED||0,f.VISITS||0)}}/></div></div><div><div className="flex justify-between text-sm"><span>Interessado → demo</span><b>{pct(f.DEMOS||0,f.INTERESTED||0)}</b></div><div className="mt-2 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:pct(f.DEMOS||0,f.INTERESTED||0)}}/></div></div><div><div className="flex justify-between text-sm"><span>Proposta → cliente</span><b>{pct(f.CLIENTS||0,f.PROPOSALS||0)}</b></div><div className="mt-2 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:pct(f.CLIENTS||0,f.PROPOSALS||0)}}/></div></div></div><Link to="/" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Abrir plano de hoje <ArrowRight className="h-4 w-4"/></Link></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="font-semibold">O que está convertendo</h2><p className="mt-1 text-sm text-muted">Sinais presentes nos leads que chegaram a cliente. Use como aprendizado, não como regra absoluta.</p><div className="mt-4 space-y-3">{d.converting_signals.slice(0,6).map(s=><div key={s.signal}><div className="flex items-center justify-between gap-3 text-sm"><span>{s.signal}</span><b className="text-primary">{s.conversion_pct}%</b></div><div className="mt-1.5 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,s.conversion_pct)}%`}}/></div><p className="mt-1 text-xs text-muted">{s.clients} clientes em {s.leads} leads com esse sinal</p></div>)}</div></Card>
   <Card><h2 className="font-semibold">Desempenho da equipe</h2><p className="mt-1 text-sm text-muted">Ordenado por conversão de visitas, não apenas volume de atividade.</p><div className="mt-4 divide-y divide-border">{(d.leaderboard||[]).filter(x=>x.member!=='sistema').slice(0,8).map((x,i)=><div key={x.member} className="flex items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-primary-soft text-xs font-bold text-primary">{i+1}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{x.member}</b><span className="text-xs text-muted">{x.visits} visitas · {x.activities} atividades</span></div><div className="text-right"><b className="text-sm">{x.clients} clientes</b><span className="block text-xs text-primary">{x.conversion_pct}%</span></div></div>)}{!(d.leaderboard||[]).length&&<p className="py-4 text-sm text-muted">Ainda não há histórico suficiente por usuário.</p>}</div></Card></div>
  <div className="grid gap-5 xl:grid-cols-3"><Card><h2 className="font-semibold">Campanhas</h2><div className="mt-4 space-y-3">{d.campaigns.slice(0,6).map(c=><div key={c.name} className="flex items-center justify-between gap-3"><div><b className="text-sm">{c.name}</b><p className="text-xs text-muted">{c.leads} leads · {money(Number(c.mrr||0))} MRR</p></div><span className="text-sm font-semibold text-primary">{pct(c.clients,c.leads)}</span></div>)}</div></Card><Card><h2 className="font-semibold">Objeções frequentes</h2><div className="mt-4 space-y-2">{d.objections.slice(0,7).map(o=><div key={o.code} className="flex justify-between text-sm"><span>{o.label}</span><b>{o.count}</b></div>)}{!d.objections.length&&<p className="text-sm text-muted">Sem objeções registradas.</p>}</div></Card><Card><h2 className="font-semibold">Teste de abordagem</h2><div className="mt-4 space-y-3">{d.pitch_ab.map(p=><div key={p.variant} className="rounded-xl border border-border p-3"><div className="flex justify-between"><b className="text-sm">Pitch {p.variant}</b><span className="text-sm font-semibold text-primary">{pct(p.clients,p.leads)}</span></div><p className="mt-1 text-xs text-muted">{p.positives} respostas positivas · {p.clients} clientes</p></div>)}</div></Card></div>
  <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Próxima ação</h2><p className="mt-1 text-sm text-muted">Escolha uma área e gere uma nova lista priorizada quando a operação estiver pronta para mais leads.</p></div><Link to="/search" className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Buscar leads <ArrowRight className="h-4 w-4"/></Link></div></Card>
 </div>
}
