import {useQuery} from '@tanstack/react-query'
import {api} from '@/services/api'
import {Card} from '@/components/ui/Card'
import type {AdvancedDashboard} from '@/types'
import {Link} from 'react-router-dom'
import {ArrowRight} from 'lucide-react'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'

const pct=(a:number,b:number)=>b?`${(100*a/b).toFixed(1)}%`:'0%'
export function DashboardPage(){
 const q=useQuery({queryKey:['dashboard-advanced'],queryFn:()=>api.get<AdvancedDashboard>('/api/dashboard/advanced')});const d=q.data
 if(!d)return <p className="text-muted">Carregando dashboard...</p>
 const f=d.funnel||{};const funnel=[['Leads',f.LEADS||0],['Contatos',f.CONTACTS||0],['Visitas',f.VISITS||0],['Interessados',f.INTERESTED||0],['Demos',f.DEMOS||0],['Propostas',f.PROPOSALS||0],['Clientes',f.CLIENTS||0]]
 const cards=[['Leads',d.summary.total||0],['Prioridade alta',d.summary.hot||0],['Visitados',d.summary.visited||0],['Interessados',d.summary.interested||0],['Clientes',d.summary.clients||0],['Sem site',d.summary.no_website||0]]
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Dashboard</h1><p className="mt-1 text-sm text-muted">Conversão, campanhas, objeções e uso da operação comercial.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([l,v])=><Card key={String(l)}><p className="text-sm text-muted">{l}</p><p className="mt-2 text-3xl font-bold">{v}</p></Card>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><h2 className="font-semibold">Funil completo</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{funnel.map(([label,value],i)=><div key={String(label)} className="rounded-xl border border-border p-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p>{i>0&&<p className="mt-1 text-xs text-subtle">{pct(Number(value),Number(funnel[i-1][1]))} da etapa anterior</p>}</div>)}</div></Card><Card><h2 className="font-semibold">Uso de IA hoje</h2><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-xs text-muted">Chamadas</p><p className="text-2xl font-bold">{d.ai_usage.calls}</p></div><div><p className="text-xs text-muted">Custo estimado</p><p className="text-2xl font-bold">US$ {d.ai_usage.cost_usd.toFixed(4)}</p></div><div><p className="text-xs text-muted">Tokens entrada</p><p className="font-semibold">{d.ai_usage.input_tokens}</p></div><div><p className="text-xs text-muted">Tokens saída</p><p className="font-semibold">{d.ai_usage.output_tokens}</p></div></div></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="font-semibold">Conversão por campanha</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={d.campaigns.slice(0,10)}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" hide/><YAxis/><Tooltip/><Bar dataKey="leads" name="Leads" fill="#c7d2fe"/><Bar dataKey="clients" name="Clientes" fill="#4338ca"/></BarChart></ResponsiveContainer></div><div className="mt-3 space-y-2">{d.campaigns.slice(0,5).map(c=><div key={c.name} className="flex justify-between text-sm"><span>{c.name}</span><span className="font-semibold">{c.clients}/{c.leads} · {pct(c.clients,c.leads)}</span></div>)}</div></Card><Card><h2 className="font-semibold">Conversão por fonte</h2><div className="mt-4 space-y-3">{d.providers.map(p=><div key={p.name} className="rounded-xl border border-border p-3"><div className="flex justify-between"><b className="text-sm">{p.name}</b><span className="text-sm font-semibold text-primary">{pct(p.clients,p.leads)}</span></div><p className="mt-1 text-xs text-muted">{p.clients} clientes em {p.leads} leads</p></div>)}</div></Card></div>
  <div className="grid gap-5 xl:grid-cols-3"><Card><h2 className="font-semibold">Objeções mais comuns</h2><div className="mt-4 space-y-2">{d.objections.slice(0,8).map(o=><div key={o.code} className="flex justify-between text-sm"><span>{o.label}</span><b>{o.count}</b></div>)}{!d.objections.length&&<p className="text-sm text-muted">Ainda não há objeções registradas.</p>}</div></Card><Card><h2 className="font-semibold">Motivos de perda</h2><div className="mt-4 space-y-2">{d.losses.slice(0,8).map(o=><div key={o.reason} className="flex justify-between text-sm"><span>{o.reason}</span><b>{o.count}</b></div>)}{!d.losses.length&&<p className="text-sm text-muted">Ainda não há perdas registradas.</p>}</div></Card><Card><h2 className="font-semibold">Teste A/B de abordagem</h2><div className="mt-4 space-y-3">{d.pitch_ab.map(p=><div key={p.variant} className="rounded-xl border border-border p-3"><b className="text-sm">Pitch {p.variant}</b><p className="mt-1 text-xs text-muted">{p.positives} respostas positivas · {p.clients} clientes · {pct(p.clients,p.leads)} conversão final</p></div>)}</div></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="font-semibold">O que está convertendo</h2><p className="mt-1 text-sm text-muted">Sinais que aparecem nos leads que chegaram a cliente. Quanto mais histórico real houver, mais útil essa leitura fica.</p><div className="mt-4 space-y-3">{d.converting_signals.map(s=><div key={s.signal} className="rounded-xl border border-border p-3"><div className="flex justify-between gap-3"><b className="text-sm">{s.signal}</b><span className="text-sm font-semibold text-primary">{s.conversion_pct}%</span></div><p className="mt-1 text-xs text-muted">{s.clients} clientes em {s.leads} leads com esse sinal</p></div>)}</div></Card><Card><h2 className="font-semibold">Conversão por perfil de score</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{d.converting.map(c=><div key={c.profile} className="rounded-xl border border-border p-4"><b>{c.profile}</b><p className="mt-2 text-2xl font-bold text-primary">{c.clients}</p><p className="text-xs text-muted">clientes em {c.leads} leads · {pct(c.clients,c.leads)}</p>{c.avg_client_opportunity!=null&&<p className="mt-2 text-xs text-muted">Score médio de oportunidade dos clientes: {c.avg_client_opportunity}</p>}</div>)}</div></Card></div>
  <Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Próxima ação</h2><p className="mt-1 text-sm text-muted">Escolha uma área no mapa e gere uma lista priorizada de negócios locais.</p></div><Link to="/search" className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Buscar leads <ArrowRight className="h-4 w-4"/></Link></div></Card>
 </div>
}
