import {useState} from 'react'
import {useMutation,useQuery} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {BrainCircuit,Search,Sparkles,TrendingUp,Target,ArrowRight,MessageSquareText} from 'lucide-react'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {api} from '@/services/api'
import type {IntelligenceOverview,Lead} from '@/types'
import {Card} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import {Badge} from '@/components/ui/Badge'
import {PageSkeleton} from '@/components/ui/Skeleton'

export function IntelligencePage(){
 const overview=useQuery({queryKey:['intelligence-overview'],queryFn:()=>api.get<IntelligenceOverview>('/api/intelligence/overview')})
 const[natural,setNatural]=useState('barbearias sem agendamento, não visitadas, score acima de 75')
 const[question,setQuestion]=useState('Quem eu deveria visitar hoje?')
 const query=useMutation({mutationFn:()=>api.post<any>('/api/intelligence/query',{query:natural})})
 const copilot=useMutation({mutationFn:()=>api.post<any>('/api/intelligence/copilot',{question})})
 const d=overview.data
 if(!d)return <PageSkeleton/>
 return <div className="space-y-7">
  <div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Decisão comercial</p><h1 className="mt-1 text-3xl font-bold">Inteligência</h1><p className="mt-1 max-w-3xl text-sm text-muted">O Lead Search cruza resultados reais do CRM com maturidade digital, aderência, probabilidade e valor esperado para ajudar a decidir onde gastar tempo.</p></div>
  <div className="grid gap-4 sm:grid-cols-3"><Card><p className="text-xs font-semibold uppercase text-muted">Base analisada</p><p className="mt-2 text-3xl font-bold">{d.totals.leads}</p><p className="text-xs text-muted">leads utilizáveis</p></Card><Card><p className="text-xs font-semibold uppercase text-muted">Clientes observados</p><p className="mt-2 text-3xl font-bold">{d.totals.clients}</p><p className="text-xs text-muted">usados no aprendizado</p></Card><Card><p className="text-xs font-semibold uppercase text-muted">Valor esperado da carteira</p><p className="mt-2 text-3xl font-bold">{d.totals.expected_mrr.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p><p className="text-xs text-muted">MRR × probabilidade, não previsão garantida</p></Card></div>

  <div className="grid gap-5 xl:grid-cols-[1.05fr_.95fr]">
   <Card><div className="flex items-center gap-2"><Search className="h-5 w-5 text-primary"/><h2 className="font-semibold">Pesquisa em linguagem natural</h2></div><p className="mt-1 text-sm text-muted">Use frases comerciais em vez de montar vários filtros.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input className="h-11 flex-1 rounded-xl border border-border bg-surface px-3 text-sm" value={natural} onChange={e=>setNatural(e.target.value)}/><Button onClick={()=>query.mutate()} disabled={query.isPending}>Pesquisar</Button></div>{query.data&&<div className="mt-4"><div className="mb-2 flex items-center justify-between"><b className="text-sm">{query.data.count} encontrados</b><span className="text-xs text-muted">filtro interpretado automaticamente</span></div><div className="max-h-80 space-y-2 overflow-auto">{(query.data.results||[]).slice(0,12).map((l:Lead)=><Link key={l.business_key} to={`/leads/${encodeURIComponent(l.business_key)}`} className="flex items-center justify-between rounded-xl border border-border p-3 hover:bg-surface-hover"><div className="min-w-0"><b className="block truncate text-sm">{l.name}</b><p className="truncate text-xs text-muted">{l.category||l.address}</p></div><div className="ml-3 text-right"><b className="text-primary">{l.visit_priority_score||0}</b><p className="text-[10px] text-muted">prioridade</p></div></Link>)}</div></div>}</Card>
   <Card><div className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-primary"/><h2 className="font-semibold">Copiloto comercial</h2></div><p className="mt-1 text-sm text-muted">Pergunte sobre prioridade, segmentos, pitch ou perdas. A resposta usa a base do CRM.</p><textarea className="mt-4 min-h-24 w-full rounded-xl border border-border bg-surface p-3 text-sm" value={question} onChange={e=>setQuestion(e.target.value)}/><Button className="mt-2" onClick={()=>copilot.mutate()} disabled={copilot.isPending}><MessageSquareText className="h-4 w-4"/>Analisar</Button>{copilot.data&&<div className="mt-4 rounded-xl bg-primary-soft p-4"><b className="text-sm text-primary">Resposta</b><p className="mt-2 text-sm leading-6">{copilot.data.answer}</p></div>}</Card>
  </div>

  {d.suggested_icp&&<Card className="border-primary/20 bg-primary-soft/40"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">ICP sugerido pelos resultados</p><h2 className="mt-1 text-xl font-bold">{d.suggested_icp.segment}</h2><p className="mt-1 text-sm text-muted">Conversão observada de {d.suggested_icp.observed_conversion_pct}% em {d.suggested_icp.sample_size} leads. Confiança {d.suggested_icp.confidence}; use como hipótese comercial, não como regra definitiva.</p></div><Badge tone="primary">{d.suggested_icp.confidence}</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-surface p-3"><p className="text-xs text-muted">Sem agenda online</p><b>{Number(d.suggested_icp.signals.without_online_booking_pct||0).toFixed(0)}%</b></div><div className="rounded-xl bg-surface p-3"><p className="text-xs text-muted">Negócios locais</p><b>{Number(d.suggested_icp.signals.local_business_pct||0).toFixed(0)}%</b></div><div className="rounded-xl bg-surface p-3"><p className="text-xs text-muted">Mediana de avaliações</p><b>{Number(d.suggested_icp.signals.median_reviews||0).toFixed(0)}</b></div></div></Card>}

  <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Target className="h-5 w-5 text-primary"/><h2 className="font-semibold">Próximas melhores oportunidades</h2></div><p className="mt-1 text-sm text-muted">Ordenação por prioridade, aderência e valor esperado. Use como recomendação, não como decisão automática.</p></div><Badge tone="primary">Top {Math.min(10,d.recommended.length)}</Badge></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{d.recommended.slice(0,10).map((x,i)=><Link key={x.lead.business_key} to={`/leads/${encodeURIComponent(x.lead.business_key)}`} className="rounded-xl border border-border p-4 transition hover:bg-surface-hover"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-semibold text-primary">#{i+1}</span><b className="ml-2 text-sm">{x.lead.name}</b><p className="mt-1 text-xs text-muted">{x.lead.category||'Sem segmento'}</p></div><span className="rounded-lg bg-primary-soft px-2 py-1 text-xs font-bold text-primary">{x.lead.visit_priority_score||0}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-background p-2"><b>{x.intelligence.commercial_fit_score}</b><span className="block text-muted">fit</span></div><div className="rounded-lg bg-background p-2"><b>{x.intelligence.conversion_probability}%</b><span className="block text-muted">prob.</span></div><div className="rounded-lg bg-background p-2"><b>{x.intelligence.expected_mrr_value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</b><span className="block text-muted">valor esp.</span></div></div></Link>)}</div></Card>

  <div className="grid gap-5 xl:grid-cols-2"><Card><div className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-primary"/><h2 className="font-semibold">Conversão observada por segmento</h2></div><div className="mt-4 h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={d.segments.slice(0,8)} layout="vertical" margin={{left:20,right:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" domain={[0,100]} unit="%"/><YAxis type="category" dataKey="name" width={120} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="conversion_pct" name="Conversão %" fill="currentColor" className="text-primary" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer></div></Card><Card><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary"/><h2 className="font-semibold">O que está funcionando</h2></div><div className="mt-4 space-y-3">{d.insights.map((x,i)=><div key={i} className="rounded-xl border border-border p-4 text-sm leading-6">{x}</div>)}{d.signals.slice(0,6).map(x=><div key={x.signal} className="flex items-center justify-between gap-3 rounded-xl bg-background p-3"><div><b className="text-sm">{x.signal}</b><p className="text-xs text-muted">{x.clients} clientes em {x.leads} leads</p></div><div className="text-right"><b className="text-primary">{x.conversion_pct}%</b><p className="text-[10px] text-muted">conversão</p></div></div>)}</div></Card></div>
 </div>
}
