import {useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from '@/services/api'
import type {Lead} from '@/types'
import {useParams,useSearchParams,Link} from 'react-router-dom'
import {Card} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import {Badge} from '@/components/ui/Badge'
import {ACTIVITY_TYPES,OBJECTIONS,OBJECTION_PLAYBOOK,PIPELINE} from '@/lib/options'
import {AlertTriangle,ArrowLeft,ExternalLink,Phone,CalendarPlus,Navigation,RefreshCcw,Copy,UserRoundSearch,ShieldCheck} from 'lucide-react'
import {VoiceNoteButton} from '@/components/productivity/VoiceNoteButton'

function localValue(v?:string){if(!v)return '';const d=new Date(v);if(Number.isNaN(d.getTime()))return '';const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
export function LeadDetailPage(){
 const{key}=useParams();const[sp]=useSearchParams();const jobId=sp.get('jobId');const qc=useQueryClient()
 const q=useQuery({queryKey:['lead',key],queryFn:()=>api.get<Lead>(`/api/leads/${key}`),enabled:!!key});const evolution=useQuery({queryKey:['evolution',key],queryFn:()=>api.get<any>(`/api/leads/${key}/evolution`),enabled:!!key})
 const l=q.data
 const[status,setStatus]=useState('NEW'),[assigned,setAssigned]=useState(''),[contact,setContact]=useState(''),[phone,setPhone]=useState(''),[nextAction,setNextAction]=useState(''),[notes,setNotes]=useState(''),[lostReason,setLostReason]=useState(''),[dnc,setDnc]=useState(false),[mrr,setMrr]=useState(89.9)
 const[activityType,setActivityType]=useState('CALL'),[activityDetails,setActivityDetails]=useState(''),[activityOutcome,setActivityOutcome]=useState('')
 const[objection,setObjection]=useState('PRICE'),[objectionDetails,setObjectionDetails]=useState('')
 const[followTitle,setFollowTitle]=useState('Retornar contato'),[followDue,setFollowDue]=useState(''),[followNotes,setFollowNotes]=useState('');const[msg,setMsg]=useState('')
 useEffect(()=>{if(!l)return;setStatus(l.pipeline_status||'NEW');setAssigned(l.assigned_to||'');setContact(l.contact_name||'');setPhone(l.contact_phone||l.phone||'');setNextAction(localValue(l.next_action_at));setNotes(l.notes||'');setLostReason(l.lost_reason||'');setDnc(!!l.do_not_contact);setMrr(l.estimated_mrr||89.9)},[l])
 const refresh=()=>{qc.invalidateQueries({queryKey:['lead',key]});qc.invalidateQueries({queryKey:['evolution',key]})}
 const save=useMutation({mutationFn:()=>api.patch(`/api/leads/${key}`,{pipeline_status:status,assigned_to:assigned,contact_name:contact,contact_phone:phone,next_action_at:nextAction?new Date(nextAction).toISOString():null,notes,lost_reason:lostReason,do_not_contact:dnc,estimated_mrr:mrr}),onSuccess:refresh})
 const addActivity=useMutation({mutationFn:()=>api.post(`/api/leads/${key}/activities`,{activity_type:activityType,details:activityDetails,outcome:activityOutcome}),onSuccess:()=>{setActivityDetails('');setActivityOutcome('');refresh()}})
 const checkin=useMutation({mutationFn:()=>new Promise<any>((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>api.post(`/api/leads/${key}/activities`,{activity_type:'ARRIVED',details:'Check-in presencial',outcome:'ARRIVED',lat:p.coords.latitude,lon:p.coords.longitude}).then(resolve).catch(reject),reject,{enableHighAccuracy:true,timeout:8000})),onSuccess:refresh})
 const addObjection=useMutation({mutationFn:()=>{const found=OBJECTIONS.find(x=>x[0]===objection)!;return api.post(`/api/leads/${key}/objections`,{code:found[0],label:found[1],details:objectionDetails})},onSuccess:()=>{setObjectionDetails('');refresh()}})
 const quick=useMutation({mutationFn:(outcome:string)=>api.post(`/api/leads/${key}/outcomes`,{outcome,notes,objection_code:undefined,objection_label:undefined,objection_details:''}),onSuccess:refresh})
 const follow=useMutation({mutationFn:()=>api.post('/api/followups',{business_key:key,title:followTitle,due_at:new Date(followDue).toISOString(),notes:followNotes}),onSuccess:()=>{setFollowNotes('');refresh()}})
 const reanalyze=useMutation({mutationFn:()=>api.post<Lead>(`/api/leads/${key}/reanalysis/run`),onSuccess:refresh})
 const schedule=useMutation({mutationFn:()=>api.post(`/api/leads/${key}/reanalysis/schedule`,{days:30}),onSuccess:refresh})
 const message=useMutation({mutationFn:()=>api.post<{message:string}>(`/api/leads/${key}/post-visit-message`,{notes}),onSuccess:d=>setMsg(d.message)})
 const aiRisk=useMemo(()=>!!l&&(!l.website||l.site_functional===false||l.robots_noindex||(l.ai_search_readiness_score||0)<50),[l])
 if(!l)return <p className="text-muted">Carregando...</p>
 const quickActions=[['VISITED','Visitado'],['NO_OWNER','Responsável não estava'],['INTERESTED','Interessado'],['DEMO','Demonstração'],['PROPOSAL','Proposta'],['CLIENT','Cliente'],['NOT_INTERESTED','Sem interesse']]
 const playbook=OBJECTION_PLAYBOOK[objection]
 return <div className="space-y-6"><Link to={jobId?`/leads?jobId=${jobId}`:'/leads'} className="inline-flex items-center gap-2 text-sm font-medium text-muted"><ArrowLeft className="h-4 w-4"/>Voltar</Link>
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{l.name}</h1><p className="mt-1 text-sm text-muted">{l.address}</p><div className="mt-3 flex flex-wrap gap-2"><Badge tone="primary">Prioridade {l.visit_priority_score||0}</Badge><Badge tone="neutral">Oportunidade {l.opportunity_score||0}</Badge><Badge tone={l.is_large_chain?'danger':'success'}>{l.is_large_chain?'Grande rede':`Aderência ${l.target_fit_score||0}`}</Badge><Badge tone="neutral">{l.campaign_name||'Sem campanha'}</Badge>{l.aging_label&&<Badge tone={l.aging_days&&l.aging_days>=30?'warning':'neutral'}>{l.aging_label}</Badge>}</div></div><div className="flex flex-wrap gap-2">{l.phone&&<a className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm font-medium" href={`tel:${l.phone}`}><Phone className="h-4 w-4"/>Ligar</a>}{l.website&&<a className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-surface px-3 text-sm font-medium" href={l.website} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/>Site</a>}<Link className="inline-flex h-10 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-white" to={`/reports/${encodeURIComponent(l.business_key)}${jobId?`?jobId=${jobId}`:''}`}>Relatório para o lead</Link></div></div>
  {l.next_best_action&&<Card className="border-primary/30 bg-primary-soft"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Próxima melhor ação</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-primary">{l.next_best_action.label}</h2><p className="mt-1 text-sm text-ink">{l.next_best_action.reason}</p></div><Badge tone="primary">prioridade {l.next_best_action.priority}</Badge></div></Card>}
  {aiRisk&&<section className="rounded-2xl border border-red-200 bg-danger-soft p-5"><div className="flex gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-danger"/><div><h2 className="font-semibold text-danger">Presença digital com risco de perder competitividade na busca com IA</h2><p className="mt-2 text-sm leading-6 text-red-900">O Google informa que AI Overviews e AI Mode usam conteúdo do índice da Pesquisa. Um negócio sem site próprio funcional e rastreável não desaparece automaticamente — o Perfil da Empresa continua importante —, mas tem menos conteúdo próprio controlável para ser encontrado, compreendido e citado nessas experiências.</p></div></div></section>}
  <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-5">
   <Card><h2 className="font-semibold">Dores detectadas</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{(l.pains||[]).map(p=><div key={p.code} className="rounded-xl border border-border p-3"><div className="flex items-center gap-2"><Badge tone={p.severity==='high'?'danger':p.severity==='medium'?'warning':'neutral'}>{p.severity==='high'?'Alta':p.severity==='medium'?'Média':'Sinal'}</Badge><b className="text-sm">{p.label}</b></div><p className="mt-2 text-xs leading-5 text-muted">{p.evidence}</p></div>)}{!(l.pains||[]).length&&<p className="text-sm text-muted">Nenhuma dor digital forte identificada.</p>}</div></Card>
   <Card><h2 className="font-semibold">Ações rápidas</h2><div className="mt-4 flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>checkin.mutate()} disabled={checkin.isPending}><Navigation className="h-4 w-4"/>Cheguei</Button>{quickActions.map(([v,label])=><Button key={v} variant={v==='CLIENT'?'primary':'secondary'} disabled={quick.isPending} onClick={()=>quick.mutate(v)}>{label}</Button>)}</div></Card>
   <Card className="space-y-4"><div><h2 className="font-semibold">CRM completo</h2><p className="mt-1 text-sm text-muted">Dados de relacionamento e próxima ação.</p></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Etapa<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={status} onChange={e=>setStatus(e.target.value)}>{PIPELINE.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="text-sm font-medium">Responsável<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={assigned} onChange={e=>setAssigned(e.target.value)} placeholder="E-mail ou nome"/></label><label className="text-sm font-medium">Contato no estabelecimento<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={contact} onChange={e=>setContact(e.target.value)} placeholder="Dono/gerente"/></label><label className="text-sm font-medium">Telefone<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="text-sm font-medium">Próxima ação<input type="datetime-local" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={nextAction} onChange={e=>setNextAction(e.target.value)}/></label><label className="text-sm font-medium">MRR estimado<input type="number" step="0.01" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={mrr} onChange={e=>setMrr(Number(e.target.value))}/></label><label className="text-sm font-medium md:col-span-2">Motivo de perda<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={lostReason} onChange={e=>setLostReason(e.target.value)}/></label><label className="text-sm font-medium md:col-span-2">Notas<textarea className="mt-1 min-h-24 w-full rounded-lg border border-border p-3" value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="md:col-span-2"><VoiceNoteButton onText={t=>setNotes(n=>`${n}${n?' ':''}${t}`)}/></div><label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" checked={dnc} onChange={e=>setDnc(e.target.checked)}/>Não contatar novamente</label></div><div className="flex justify-end"><Button onClick={()=>save.mutate()} disabled={save.isPending}>{save.isPending?'Salvando...':'Salvar CRM'}</Button></div></Card>
   <Card className="space-y-4"><h2 className="font-semibold">Registrar atividade</h2><div className="grid gap-3 md:grid-cols-3"><select className="h-10 rounded-lg border border-border bg-surface px-3" value={activityType} onChange={e=>setActivityType(e.target.value)}>{ACTIVITY_TYPES.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><input className="h-10 rounded-lg border border-border px-3" placeholder="Resultado/status" value={activityOutcome} onChange={e=>setActivityOutcome(e.target.value)}/><Button onClick={()=>addActivity.mutate()}>Registrar</Button></div><textarea className="min-h-20 w-full rounded-lg border border-border p-3" value={activityDetails} onChange={e=>setActivityDetails(e.target.value)}/><VoiceNoteButton onText={t=>setActivityDetails(n=>`${n}${n?' ':''}${t}`)} label="Ditado da atividade"/></Card>
   <Card className="space-y-4"><h2 className="font-semibold">Objeção e playbook</h2><div className="grid gap-3 md:grid-cols-[240px_1fr_auto]"><select className="h-10 rounded-lg border border-border bg-surface px-3" value={objection} onChange={e=>setObjection(e.target.value)}>{OBJECTIONS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select><input className="h-10 rounded-lg border border-border px-3" placeholder="Contexto" value={objectionDetails} onChange={e=>setObjectionDetails(e.target.value)}/><Button variant="secondary" onClick={()=>addObjection.mutate()}>Registrar</Button></div><div className="rounded-xl bg-background p-3 text-sm text-muted"><b className="text-ink">Sugestão de resposta:</b> {playbook}</div></Card>
  </div><div className="space-y-5">
   <Card><h2 className="font-semibold">Diagnóstico comercial</h2><p className="mt-3 text-sm leading-6 text-muted">{l.why_approach||'Análise ainda não disponível.'}</p><div className="mt-4 rounded-xl bg-primary-soft p-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Abordagem sugerida</p><p className="mt-2 text-sm leading-6 text-ink">{l.sales_pitch||'Use os gaps digitais identificados para iniciar a conversa.'}</p></div><p className="mt-3 text-xs text-muted">{l.reputation_insight}</p></Card>
   <Card><div className="flex items-center gap-2"><UserRoundSearch className="h-4 w-4 text-primary"/><h2 className="font-semibold">Decisor e confiança dos dados</h2></div>{l.decision_maker_name?<div className="mt-3"><b>{l.decision_maker_name}</b><p className="text-sm text-muted">{l.decision_maker_role||'Possível responsável'} · confiança {l.decision_maker_confidence||0}%</p></div>:<p className="mt-3 text-sm text-muted">Nenhum decisor identificado com confiança suficiente.</p>}<div className="mt-4 space-y-2">{(l.field_evidence||[]).slice(0,8).map(e=><div key={e.field} className="flex items-center justify-between gap-3 rounded-lg border border-border p-2 text-xs"><span><b>{e.label}</b><span className="ml-2 text-muted">{e.source}</span></span><span className="font-semibold">{e.confidence}%</span></div>)}</div></Card>
   <Card className="space-y-4"><div className="flex items-center gap-2"><CalendarPlus className="h-4 w-4 text-primary"/><h2 className="font-semibold">Follow-up manual</h2></div><input className="h-10 w-full rounded-lg border border-border px-3" value={followTitle} onChange={e=>setFollowTitle(e.target.value)}/><input type="datetime-local" className="h-10 w-full rounded-lg border border-border px-3" value={followDue} onChange={e=>setFollowDue(e.target.value)}/><textarea className="min-h-20 w-full rounded-lg border border-border p-3" value={followNotes} onChange={e=>setFollowNotes(e.target.value)}/><Button className="w-full" variant="secondary" disabled={!followDue||follow.isPending} onClick={()=>follow.mutate()}>Criar follow-up</Button></Card>
   <Card className="space-y-3"><h2 className="font-semibold">Mensagem pós-visita</h2><Button variant="secondary" onClick={()=>message.mutate()}>Gerar mensagem</Button>{msg&&<div className="rounded-xl bg-background p-3 text-sm leading-6"><p>{msg}</p><button className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-primary" onClick={()=>navigator.clipboard.writeText(msg)}><Copy className="h-3 w-3"/>Copiar</button></div>}</Card>
   <Card className="space-y-3"><h2 className="font-semibold">Reanálise da presença digital</h2><p className="text-sm text-muted">Reavalie mudanças de site, agenda e estrutura ao longo do tempo.</p><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!l.website||reanalyze.isPending} onClick={()=>reanalyze.mutate()}><RefreshCcw className="h-4 w-4"/>Reanalisar agora</Button><Button variant="secondary" onClick={()=>schedule.mutate()}>Rever em 30 dias</Button></div>{l.next_reanalysis_at&&<p className="text-xs text-muted">Próxima reanálise: {new Date(l.next_reanalysis_at).toLocaleDateString('pt-BR')}</p>}{evolution.data?.changes?.length>0&&<div className="rounded-xl bg-success-soft p-3"><div className="flex gap-2"><ShieldCheck className="h-4 w-4 text-success"/><b className="text-sm text-success">Evolução desde o diagnóstico anterior</b></div><p className="mt-1 text-xs text-success">{evolution.data.changes.length} sinais mudaram desde o snapshot mais antigo disponível.</p><div className="mt-3 space-y-2">{evolution.data.changes.slice(0,8).map((c:any)=><div key={c.field} className="rounded-lg bg-white/60 p-2 text-xs"><b>{({website:'Site',site_functional:'Site funcional',has_booking:'Agendamento online',has_catalog:'Catálogo',has_whatsapp:'WhatsApp',digital_maturity_score:'Maturidade digital',ai_search_readiness_score:'Prontidão para busca com IA',pipeline_status:'Etapa comercial'} as Record<string,string>)[c.field]||c.field}</b><div className="mt-1 text-muted">Antes: {String(c.before??'não identificado')} → Agora: {String(c.after??'não identificado')}</div></div>)}</div></div>}{evolution.data?.baseline&&<p className="text-xs text-muted">O histórico preserva o diagnóstico anterior para mostrar evolução ao longo do relacionamento.</p>}</Card>
   <Card><h2 className="font-semibold">Histórico recente</h2><div className="mt-4 space-y-3">{(l.activities||[]).slice(0,14).map(a=><div key={a.id} className="border-l-2 border-border pl-3"><div className="flex justify-between gap-2"><b className="text-sm">{a.activity_type}</b><span className="text-xs text-muted">{new Date(a.created_at).toLocaleString('pt-BR')}</span></div>{a.details&&<p className="mt-1 text-sm text-muted">{a.details}</p>}</div>)}</div></Card>
  </div></div>
 </div>
}
