import {useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery} from '@tanstack/react-query'
import {api} from '@/services/api'
import {AreaPickerMap} from '@/components/map/AreaPickerMap'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Badge} from '@/components/ui/Badge'
import type {AppSettings,SearchJob,ICP,Territory} from '@/types'
import {SCORE_PROFILES} from '@/lib/options'
import {Link} from 'react-router-dom'

export function SearchPage(){
 const [lat,setLat]=useState(-23.1896),[lon,setLon]=useState(-45.8841),[radius,setRadius]=useState(1500)
 const [place,setPlace]=useState('São José dos Campos, SP'),[provider,setProvider]=useState('auto'),[aiProvider,setAiProvider]=useState('Desativada')
 const [city,setCity]=useState('São José dos Campos'),[state,setState]=useState('São Paulo'),[district,setDistrict]=useState('')
 const [campaign,setCampaign]=useState('Prospecção geral'),[profile,setProfile]=useState('Auto'),[defaultMrr,setDefaultMrr]=useState(89.9),[maxResults,setMaxResults]=useState(300),[includeChains,setIncludeChains]=useState(false),[jobId,setJobId]=useState<number|null>(null),[icp,setIcp]=useState(''),[territoryId,setTerritoryId]=useState<number|undefined>(undefined)
 const settings=useQuery({queryKey:['settings'],queryFn:()=>api.get<AppSettings>('/api/settings')});const campaigns=useQuery({queryKey:['campaigns'],queryFn:()=>api.get<{campaign_name:string;leads:number}[]>('/api/campaigns')});const icps=useQuery({queryKey:['icps'],queryFn:()=>api.get<ICP[]>('/api/icps')});const territories=useQuery({queryKey:['territories'],queryFn:()=>api.get<Territory[]>('/api/territories')})
 useEffect(()=>{if(settings.data){setAiProvider(settings.data.default_ai_provider||'Desativada');setProfile(settings.data.default_score_profile||'Auto');setDefaultMrr(settings.data.default_mrr||89.9)}},[settings.data])
 const selectedModel=useMemo(()=>aiProvider==='Gemini'?settings.data?.gemini_model:aiProvider==='OpenRouter'?settings.data?.openrouter_model:aiProvider==='OpenAI'?settings.data?.openai_model:undefined,[aiProvider,settings.data])
 const geo=useMutation({mutationFn:()=>api.get<{lat:number;lon:number;display_name:string;city_name?:string;state_name?:string;district_name?:string}>(`/api/geocode?q=${encodeURIComponent(place)}`),onSuccess:d=>{setLat(d.lat);setLon(d.lon);setPlace(d.display_name);setCity(d.city_name||city);setState(d.state_name||state);setDistrict(d.district_name||'')}})
 const start=useMutation({mutationFn:()=>api.post<{job_id:number;discovered:number}>('/api/searches',{query_text:place,lat,lon,radius_m:radius,provider,max_results:maxResults,auto_analyze:true,ai_provider:aiProvider,ai_model:selectedModel,score_profile:profile,campaign_name:campaign||'Prospecção geral',default_mrr:defaultMrr,city_name:city,state_name:state,district_name:district,include_large_chains:includeChains,icp_name:icp||null,territory_id:territoryId||null}),onSuccess:d=>setJobId(d.job_id)})
 const job=useQuery({queryKey:['job',jobId],queryFn:()=>api.get<SearchJob>(`/api/searches/${jobId}`),enabled:!!jobId,refetchInterval:q=>['DONE','FAILED','CANCELED'].includes(q.state.data?.status||'')?false:2500});const j=job.data
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Buscar leads</h1><p className="mt-1 text-sm text-muted">Escolha uma área, configure a campanha e deixe o sistema priorizar negócios locais com maior chance de abordagem.</p></div>
  <div className="grid gap-5 xl:grid-cols-[390px_1fr]"><Card className="space-y-4">
   <label className="block text-sm font-medium">Cidade, bairro ou endereço<div className="mt-1 flex gap-2"><input className="h-10 min-w-0 flex-1 rounded-lg border border-border px-3" value={place} onChange={e=>setPlace(e.target.value)}/><Button variant="secondary" onClick={()=>geo.mutate()}>Localizar</Button></div></label>
   <label className="block text-sm font-medium">Raio da busca: <b>{(radius/1000).toFixed(1)} km</b><input type="range" min="250" max="10000" step="250" value={radius} onChange={e=>setRadius(Number(e.target.value))} className="mt-2 w-full accent-primary"/></label>
   <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Máx. estabelecimentos<input type="number" min="10" max="1000" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={maxResults} onChange={e=>setMaxResults(Number(e.target.value))}/></label><label className="text-sm font-medium">MRR padrão<input type="number" step="0.01" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={defaultMrr} onChange={e=>setDefaultMrr(Number(e.target.value))}/></label></div>
   <label className="block text-sm font-medium">Campanha<input list="campaign-list" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={campaign} onChange={e=>setCampaign(e.target.value)}/><datalist id="campaign-list">{(campaigns.data||[]).map(c=><option key={c.campaign_name} value={c.campaign_name}/>)}</datalist></label>
   <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Perfil ideal (ICP)<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={icp} onChange={e=>setIcp(e.target.value)}><option value="">Sem filtro de ICP</option>{(icps.data||[]).map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label className="text-sm font-medium">Território<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={territoryId||''} onChange={e=>{const id=e.target.value?Number(e.target.value):undefined;setTerritoryId(id);const t=(territories.data||[]).find(x=>x.id===id);if(t?.center_lat!=null&&t?.center_lon!=null){setLat(t.center_lat);setLon(t.center_lon);if(t.radius_m)setRadius(t.radius_m);if(t.city_name)setCity(t.city_name);if(t.district_name)setDistrict(t.district_name);setPlace(t.name)}}}><option value="">Área livre</option>{(territories.data||[]).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div>
   <label className="block text-sm font-medium">Perfil de score<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={profile} onChange={e=>setProfile(e.target.value)}>{SCORE_PROFILES.map(x=><option key={x}>{x}</option>)}</select></label>
   <label className="block text-sm font-medium">Fonte<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={provider} onChange={e=>setProvider(e.target.value)}><option value="auto">Automático — Geoapify + fallback</option><option value="geoapify">Geoapify</option><option value="osm">OpenStreetMap</option><option value="foursquare">Foursquare</option></select></label>
   <label className="block text-sm font-medium">IA<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={aiProvider} onChange={e=>setAiProvider(e.target.value)}><option>Desativada</option><option>Auto</option><option>Gemini</option><option>OpenRouter</option><option>OpenAI</option></select>{selectedModel&&<span className="mt-1 block text-xs text-muted">Modelo: {selectedModel}</span>}</label>
   <label className="flex items-start gap-2 rounded-xl border border-border p-3 text-sm"><input type="checkbox" className="mt-1" checked={includeChains} onChange={e=>setIncludeChains(e.target.checked)}/><span><b>Incluir grandes redes</b><span className="mt-0.5 block text-xs text-muted">Desligado por padrão: redes de fast-food, drogarias e grandes varejistas têm menor eficiência para abordagem local.</span></span></label>
   <div className="rounded-xl bg-primary-soft p-3 text-sm text-primary"><b>Centro da busca</b><div className="mt-1">{city||place}{district?` · ${district}`:''}</div><div className="mt-1 text-xs">{lat.toFixed(5)}, {lon.toFixed(5)}</div></div>
   <Button className="w-full" disabled={start.isPending} onClick={()=>start.mutate()}>{start.isPending?'Iniciando...':'Buscar estabelecimentos'}</Button>{start.error&&<p className="text-sm text-danger">{start.error.message}</p>}
  </Card><Card className="p-2"><AreaPickerMap lat={lat} lon={lon} radius={radius} onChange={(a,b)=>{setLat(a);setLon(b);setPlace('Ponto selecionado no mapa')}}/></Card></div>
  {j&&<Card><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="font-semibold">Processamento #{j.id}</h2><Badge tone={j.status==='DONE'?'success':j.status==='FAILED'?'danger':'primary'}>{j.status==='DONE'?'Concluído':j.status==='FAILED'?'Falhou':'Analisando'}</Badge></div><p className="mt-1 text-sm text-muted">{j.processed_items}/{j.total_items} analisados · {j.new_items} novos · {j.reused_items} reaproveitados</p></div>{j.status==='DONE'&&<Link to={`/leads?jobId=${j.id}`} className="text-sm font-semibold text-primary">Abrir ranking</Link>}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-background"><div className="h-full bg-primary transition-all" style={{width:`${j.total_items?Math.round(100*(j.processed_items+j.failed_items)/j.total_items):0}%`}}/></div>{!!j.results?.length&&<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{j.results.slice(0,6).map(l=><Link key={l.business_key} to={`/leads/${encodeURIComponent(l.business_key)}?jobId=${j.id}`} className="rounded-xl border border-border p-4 hover:bg-surface-hover"><div className="flex justify-between gap-3"><b>{l.name}</b><span className="font-bold text-primary">{l.visit_priority_score||l.opportunity_score||0}</span></div><p className="mt-1 line-clamp-1 text-sm text-muted">{l.address}</p></Link>)}</div>}</Card>}
 </div>
}
