import {useEffect,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from '@/services/api'
import {Card} from '@/components/ui/Card'
import {Button} from '@/components/ui/Button'
import type {AppSettings,ICP,ProviderHealth,Territory} from '@/types'
import {SCORE_PROFILES} from '@/lib/options'
import {Download,ShieldCheck,ServerCog} from 'lucide-react'

export function SettingsPage(){
 const qc=useQueryClient();const q=useQuery({queryKey:['settings'],queryFn:()=>api.get<AppSettings>('/api/settings')});const health=useQuery({queryKey:['provider-health'],queryFn:()=>api.get<ProviderHealth>('/api/health/providers'),refetchInterval:60000});const providerUsage=useQuery({queryKey:['provider-usage'],queryFn:()=>api.get<any[]>('/api/usage/providers?days=30')});const territories=useQuery({queryKey:['territories'],queryFn:()=>api.get<Territory[]>('/api/territories')});const icps=useQuery({queryKey:['icps'],queryFn:()=>api.get<ICP[]>('/api/icps')});const audit=useQuery({queryKey:['audit'],queryFn:()=>api.get<any[]>('/api/audit?limit=30')})
 const [form,setForm]=useState<AppSettings>({default_mrr:89.9,default_score_profile:'Auto',default_ai_provider:'Desativada',ai_min_score:60,ai_daily_call_limit:100,ai_daily_budget_usd:2,ai_limit_per_batch:8,gemini_model:'gemini-3.7-flash',openrouter_model:'openrouter/free',openai_model:'gpt-5.6-luna',route_mode:'driving-car',route_available_minutes:240,route_visit_minutes:15,route_max_stops:12})
 const[tName,setTName]=useState('Centro'),[tCity,setTCity]=useState('São José dos Campos'),[tDistrict,setTDistrict]=useState('Centro'),[tLat,setTLat]=useState(-23.1896),[tLon,setTLon]=useState(-45.8841),[tRadius,setTRadius]=useState(2000)
 const[iName,setIName]=useState('Negócios locais prioritários'),[iInclude,setIInclude]=useState('barbearia,salão,papelaria,loja,clínica,pet shop,oficina'),[iExclude,setIExclude]=useState('fast food,hipermercado,drogaria'),[iFit,setIFit]=useState(70)
 useEffect(()=>{if(q.data)setForm(f=>({...f,...q.data}))},[q.data]);const save=useMutation({mutationFn:()=>api.patch<AppSettings>('/api/settings',form),onSuccess:d=>{setForm(d);qc.setQueryData(['settings'],d)}});const set=<K extends keyof AppSettings>(k:K,v:AppSettings[K])=>setForm(f=>({...f,[k]:v}));const usage=q.data?.ai_usage_today||{}
 const createTerritory=useMutation({mutationFn:()=>api.post('/api/territories',{name:tName,city_name:tCity,district_name:tDistrict,center_lat:tLat,center_lon:tLon,radius_m:tRadius}),onSuccess:()=>qc.invalidateQueries({queryKey:['territories']})})
 const createIcp=useMutation({mutationFn:()=>api.post('/api/icps',{name:iName,config:{include_terms:iInclude.split(',').map(x=>x.trim()).filter(Boolean),exclude_terms:iExclude.split(',').map(x=>x.trim()).filter(Boolean),min_target_fit:iFit,local_only:true}}),onSuccess:()=>qc.invalidateQueries({queryKey:['icps']})})
 const backup=async()=>{const data=await api.get<any>('/api/export/full');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`beesys-lead-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}
 const h=health.data
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Configurações</h1><p className="mt-1 text-sm text-muted">Padrões comerciais, IA, territórios, ICP e saúde da operação.</p></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card className="space-y-4"><h2 className="font-semibold">Comercial e score</h2><label className="block text-sm font-medium">MRR padrão por novo lead<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" type="number" step="0.01" value={form.default_mrr} onChange={e=>set('default_mrr',Number(e.target.value))}/></label><label className="block text-sm font-medium">Perfil de score padrão<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={form.default_score_profile} onChange={e=>set('default_score_profile',e.target.value)}>{SCORE_PROFILES.map(x=><option key={x}>{x}</option>)}</select></label></Card><Card className="space-y-4"><h2 className="font-semibold">Rota padrão</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Modo<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={form.route_mode} onChange={e=>set('route_mode',e.target.value)}><option value="driving-car">Carro</option><option value="foot-walking">A pé</option></select></label><label className="text-sm font-medium">Tempo disponível (min)<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.route_available_minutes} onChange={e=>set('route_available_minutes',Number(e.target.value))}/></label><label className="text-sm font-medium">Minutos por visita<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.route_visit_minutes} onChange={e=>set('route_visit_minutes',Number(e.target.value))}/></label><label className="text-sm font-medium">Máximo de paradas<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.route_max_stops} onChange={e=>set('route_max_stops',Number(e.target.value))}/></label></div></Card></div>
  <Card className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Inteligência artificial</h2><p className="mt-1 text-sm text-muted">Defina quando vale gastar IA e mantenha o custo previsível.</p></div><div className="text-right text-xs text-muted"><div>{Number(usage.calls||0)} chamadas hoje</div><div>{Number(usage.input_tokens||0)+Number(usage.output_tokens||0)} tokens · US$ {Number(usage.cost_usd||0).toFixed(4)}</div></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label className="text-sm font-medium">IA padrão<select className="mt-1 h-10 w-full rounded-lg border border-border bg-surface px-3" value={form.default_ai_provider} onChange={e=>set('default_ai_provider',e.target.value)}><option>Desativada</option><option>Auto</option><option>Gemini</option><option>OpenRouter</option><option>OpenAI</option></select></label><label className="text-sm font-medium">Score mínimo<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.ai_min_score} onChange={e=>set('ai_min_score',Number(e.target.value))}/></label><label className="text-sm font-medium">Chamadas/dia<input type="number" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.ai_daily_call_limit} onChange={e=>set('ai_daily_call_limit',Number(e.target.value))}/></label><label className="text-sm font-medium">Orçamento/dia (US$)<input type="number" step="0.1" className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.ai_daily_budget_usd} onChange={e=>set('ai_daily_budget_usd',Number(e.target.value))}/></label></div><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Modelo Gemini<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.gemini_model} onChange={e=>set('gemini_model',e.target.value)}/></label><label className="text-sm font-medium">Modelo OpenRouter<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.openrouter_model} onChange={e=>set('openrouter_model',e.target.value)}/></label><label className="text-sm font-medium">Modelo OpenAI<input className="mt-1 h-10 w-full rounded-lg border border-border px-3" value={form.openai_model} onChange={e=>set('openai_model',e.target.value)}/></label></div></Card>
  <div className="flex justify-end"><Button disabled={save.isPending} onClick={()=>save.mutate()}>{save.isPending?'Salvando...':'Salvar configurações'}</Button></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="font-semibold">Territórios comerciais</h2><p className="mt-1 text-sm text-muted">Divida a cidade em áreas para evitar duplicidade de prospecção.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className="h-10 rounded-lg border border-border px-3" value={tName} onChange={e=>setTName(e.target.value)} placeholder="Nome"/><input className="h-10 rounded-lg border border-border px-3" value={tDistrict} onChange={e=>setTDistrict(e.target.value)} placeholder="Bairro"/><input className="h-10 rounded-lg border border-border px-3" value={tCity} onChange={e=>setTCity(e.target.value)} placeholder="Cidade"/><input type="number" className="h-10 rounded-lg border border-border px-3" value={tRadius} onChange={e=>setTRadius(Number(e.target.value))} placeholder="Raio m"/><input type="number" step="0.0001" className="h-10 rounded-lg border border-border px-3" value={tLat} onChange={e=>setTLat(Number(e.target.value))}/><input type="number" step="0.0001" className="h-10 rounded-lg border border-border px-3" value={tLon} onChange={e=>setTLon(Number(e.target.value))}/></div><Button className="mt-3" variant="secondary" onClick={()=>createTerritory.mutate()}>Criar território</Button><div className="mt-4 space-y-2">{(territories.data||[]).map(t=><div key={t.id} className="rounded-lg border border-border p-3 text-sm"><b>{t.name}</b><p className="text-xs text-muted">{t.district_name||t.city_name} · raio {t.radius_m||0} m</p></div>)}</div></Card>
   <Card><h2 className="font-semibold">Perfis de cliente ideal (ICP)</h2><p className="mt-1 text-sm text-muted">Crie filtros reutilizáveis para campanhas específicas.</p><div className="mt-4 space-y-2"><input className="h-10 w-full rounded-lg border border-border px-3" value={iName} onChange={e=>setIName(e.target.value)} placeholder="Nome do ICP"/><input className="h-10 w-full rounded-lg border border-border px-3" value={iInclude} onChange={e=>setIInclude(e.target.value)} placeholder="Termos incluídos, separados por vírgula"/><input className="h-10 w-full rounded-lg border border-border px-3" value={iExclude} onChange={e=>setIExclude(e.target.value)} placeholder="Termos excluídos"/><label className="text-sm">Aderência mínima: {iFit}<input type="range" min="0" max="100" value={iFit} onChange={e=>setIFit(Number(e.target.value))} className="mt-1 w-full"/></label><Button variant="secondary" onClick={()=>createIcp.mutate()}>Salvar ICP</Button></div><div className="mt-4 space-y-2">{(icps.data||[]).map(i=><div key={i.id} className="rounded-lg border border-border p-3 text-sm"><b>{i.name}</b><p className="mt-1 text-xs text-muted">Aderência mínima {i.config.min_target_fit||0} · {i.config.local_only?'Somente locais':''}</p></div>)}</div></Card></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="font-semibold">Uso das fontes — últimos 30 dias</h2><p className="mt-1 text-sm text-muted">Contagem operacional para acompanhar consumo de Geoapify, OSM e Foursquare. Não estima cobrança quando a fonte não fornece preço por chamada ao sistema.</p><div className="mt-4 space-y-2">{(providerUsage.data||[]).map((u:any)=><div key={`${u.provider}-${u.operation}`} className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm">{u.provider}</b><span className="text-xs font-semibold text-primary">{u.calls} chamadas</span></div><p className="mt-1 text-xs text-muted">{u.operation} · {Number(u.results||0)} resultados · {Number(u.units||0).toFixed(0)} unidades registradas</p></div>)}{!(providerUsage.data||[]).length&&<p className="text-sm text-muted">Nenhum uso registrado nesta versão ainda.</p>}</div></Card><Card><h2 className="font-semibold">Custo e uso de IA</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg border border-border p-3"><p className="text-xs text-muted">Chamadas hoje</p><b className="text-xl">{Number(usage.calls||0)}</b></div><div className="rounded-lg border border-border p-3"><p className="text-xs text-muted">Custo estimado</p><b className="text-xl">US$ {Number(usage.cost_usd||0).toFixed(4)}</b></div><div className="rounded-lg border border-border p-3"><p className="text-xs text-muted">Tokens de entrada</p><b>{Number(usage.input_tokens||0)}</b></div><div className="rounded-lg border border-border p-3"><p className="text-xs text-muted">Tokens de saída</p><b>{Number(usage.output_tokens||0)}</b></div></div></Card></div>
  <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card><div className="flex items-center gap-2"><ServerCog className="h-5 w-5 text-primary"/><h2 className="font-semibold">Saúde dos serviços</h2></div>{h?<div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Banco</span><b>{h.database}</b></div><div className="flex justify-between"><span>Geoapify</span><b>{h.geoapify.configured?'Configurado':'Não configurado'}</b></div><div className="flex justify-between"><span>Roteamento</span><b>{h.routing.geoapify?'Geoapify':'Fallback'}</b></div>{Object.entries(h.ai).map(([k,v])=><div key={k} className="flex justify-between"><span>{k}</span><b>{v.configured?'Configurado':'Não configurado'}</b></div>)}<div className="flex justify-between"><span>Jobs ativos</span><b>{h.jobs.active}</b></div></div>:<p className="mt-3 text-sm text-muted">Carregando...</p>}<Button className="mt-4" variant="secondary" onClick={backup}><Download className="h-4 w-4"/>Baixar backup completo</Button></Card>
   <Card><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/><h2 className="font-semibold">Auditoria recente</h2></div><div className="mt-4 max-h-72 space-y-2 overflow-auto">{(audit.data||[]).map(a=><div key={a.id} className="rounded-lg border border-border p-2 text-xs"><b>{a.action}</b><span className="ml-2 text-muted">{a.actor_email||'sistema'}</span><p className="mt-1 text-muted">{new Date(a.created_at).toLocaleString('pt-BR')} · {a.entity_type} {a.entity_id||''}</p></div>)}</div></Card></div>
 </div>
}
