import {useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from '@/services/api'
import type {Lead,RoutePlan,RouteStop,SavedRoute} from '@/types'
import {Card} from '@/components/ui/Card'
import {Link} from 'react-router-dom'
import {Badge} from '@/components/ui/Badge'
import {Button} from '@/components/ui/Button'
import {OBJECTIONS,OBJECTION_PLAYBOOK} from '@/lib/options'
import {VoiceNoteButton} from '@/components/productivity/VoiceNoteButton'
import {MapPin,Navigation,SkipForward,X,RotateCcw,Plus,Phone,ThumbsUp,CloudOff} from 'lucide-react'
import {queueOfflineAction,listOfflineActions,removeOfflineAction} from '@/lib/offlineQueue'

const CACHE_KEY='beesys_street_route_cache_v1'
const distanceM=(a:[number,number],b:[number,number])=>{const R=6371000,toRad=(v:number)=>v*Math.PI/180;const dLat=toRad(b[0]-a[0]),dLon=toRad(b[1]-a[1]);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a[0]))*Math.cos(toRad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}

export function StreetPage(){
 const qc=useQueryClient()
 const routes=useQuery({queryKey:['routes'],queryFn:()=>api.get<SavedRoute[]>('/api/routes?limit=20')})
 const today=new Date().toISOString().slice(0,10)
 const currentMeta=(routes.data||[]).find(r=>r.route_date===today)||(routes.data||[])[0]
 const route=useQuery({queryKey:['route-street',currentMeta?.id],queryFn:()=>api.get<SavedRoute>(`/api/routes/${currentMeta!.id}`),enabled:!!currentMeta?.id})
 const fallback=useQuery({queryKey:['street-fallback'],queryFn:()=>api.get<Lead[]>('/api/leads?limit=60&min_score=50&visited=no'),enabled:!currentMeta?.id})
 const nearbyPool=useQuery({queryKey:['street-nearby'],queryFn:()=>api.get<Lead[]>('/api/leads?limit=250&min_score=75&visited=no')})
 const[objection,setObjection]=useState(''),[note,setNote]=useState('')
 const[offlineCompleted,setOfflineCompleted]=useState<Set<string>>(()=>new Set()),[queuedCount,setQueuedCount]=useState(0)
 useEffect(()=>{if(route.data)localStorage.setItem(CACHE_KEY,JSON.stringify(route.data))},[route.data])
 const cached=useMemo(()=>{try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null') as SavedRoute|null}catch{return null}},[route.data])
 const activeRoute=route.data||(!navigator.onLine?cached:null)
 const stops=(activeRoute?.stops||[]).filter(s=>!['REMOVED','COMPLETED','SKIPPED'].includes(s.status)&&!offlineCompleted.has(s.business_key))
 const nextStop=stops[0]
 const nextLead=nextStop?({business_key:nextStop.business_key,name:nextStop.name,address:nextStop.address,lat:nextStop.lat,lon:nextStop.lon,visit_priority_score:nextStop.visit_priority_score,why_approach:nextStop.why_approach,pipeline_status:nextStop.pipeline_status,notes:nextStop.lead_notes,assigned_to:nextStop.assigned_to,campaign_name:nextStop.campaign_name} as Lead):(fallback.data||[])[0]
 const briefing=useQuery({queryKey:['street-briefing',nextLead?.business_key],queryFn:()=>api.get<any>(`/api/leads/${encodeURIComponent(nextLead!.business_key)}/briefing`),enabled:!!nextLead?.business_key&&navigator.onLine})
 useEffect(()=>{let mounted=true;const sync=async()=>{const actions=await listOfflineActions().catch(()=>[]);if(mounted)setQueuedCount(actions.length);if(!navigator.onLine)return;for(const a of actions){try{if(a.method==='POST')await api.post(a.path,a.body);else await api.patch(a.path,a.body);await removeOfflineAction(a.id)}catch{break}}const left=await listOfflineActions().catch(()=>[]);if(mounted)setQueuedCount(left.length);if(!left.length){setOfflineCompleted(new Set());qc.invalidateQueries({queryKey:['route-street']});qc.invalidateQueries({queryKey:['street-fallback']})}};void sync();window.addEventListener('online',sync);return()=>{mounted=false;window.removeEventListener('online',sync)}},[qc])
 const queueAndAdvance=async(path:string,body:any,routeStatus?:string)=>{await queueOfflineAction('POST',path,body);if(activeRoute?.id&&nextLead&&routeStatus)await queueOfflineAction('PATCH',`/api/routes/${activeRoute.id}/stops/${encodeURIComponent(nextLead.business_key)}`,{status:routeStatus,reason:'Registrado offline'});if(nextLead)setOfflineCompleted(prev=>new Set([...prev,nextLead.business_key]));setQueuedCount((await listOfflineActions()).length)}
 const routeKeys=new Set((activeRoute?.stops||[]).map(s=>s.business_key))
 const nearby=useMemo(()=>{if(!nextLead)return null;return (nearbyPool.data||[]).filter(l=>!routeKeys.has(l.business_key)&&!l.is_large_chain&&!l.do_not_contact).map(l=>({lead:l,d:distanceM([nextLead.lat,nextLead.lon],[l.lat,l.lon])})).filter(x=>x.d<=450).sort((a,b)=>(b.lead.visit_priority_score||0)-(a.lead.visit_priority_score||0)||a.d-b.d)[0]||null},[nearbyPool.data,nextLead?.business_key,activeRoute?.id])
 const quick=useMutation({mutationFn:async(outcome:string)=>{if(!nextLead)throw new Error('Sem próximo lead');const found=OBJECTIONS.find(x=>x[0]===objection);const path=`/api/leads/${encodeURIComponent(nextLead.business_key)}/outcomes`;const body={outcome,notes:note,objection_code:found?.[0],objection_label:found?.[1],objection_details:note};if(!navigator.onLine){await queueAndAdvance(path,body,'COMPLETED');return {queued:true}}const result=await api.post(path,body);if(activeRoute?.id)await api.patch(`/api/routes/${activeRoute.id}/stops/${encodeURIComponent(nextLead.business_key)}`,{status:'COMPLETED',reason:''});return result},onSuccess:()=>{setNote('');setObjection('');qc.invalidateQueries({queryKey:['route-street']});qc.invalidateQueries({queryKey:['street-fallback']});qc.invalidateQueries({queryKey:['street-nearby']})}})
 const arrive=useMutation({mutationFn:()=>new Promise<any>((resolve,reject)=>{if(!nextLead)return reject(new Error('Sem lead'));navigator.geolocation.getCurrentPosition(async p=>{const path=`/api/leads/${encodeURIComponent(nextLead.business_key)}/activities`;const body={activity_type:'ARRIVED',details:'Check-in pelo Modo Rua',outcome:'ARRIVED',lat:p.coords.latitude,lon:p.coords.longitude};try{if(!navigator.onLine){await queueOfflineAction('POST',path,body);setQueuedCount((await listOfflineActions()).length);resolve({queued:true})}else resolve(await api.post(path,body))}catch(e){reject(e)}},reject,{enableHighAccuracy:true,timeout:8000})})})
 const skip=useMutation({mutationFn:async(status:'SKIPPED'|'REMOVED')=>{if(!activeRoute?.id||!nextLead)return {};const path=`/api/routes/${activeRoute.id}/stops/${encodeURIComponent(nextLead.business_key)}`;const body={status,reason:status==='SKIPPED'?'Pulado durante a rota':'Removido da rota no modo rua'};if(!navigator.onLine){await queueOfflineAction('PATCH',path,body);setOfflineCompleted(prev=>new Set([...prev,nextLead.business_key]));setQueuedCount((await listOfflineActions()).length);return {queued:true}}return api.patch(path,body)},onSuccess:()=>qc.invalidateQueries({queryKey:['route-street']})})
 const replan=useMutation({mutationFn:()=>new Promise<any>((resolve,reject)=>{if(!activeRoute?.id||!stops.length)return reject(new Error('Sem rota ativa'));navigator.geolocation.getCurrentPosition(async p=>{try{const remaining=stops.map(s=>s.business_key);const now=new Date();const startLocal=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,19);const plan=await api.post<RoutePlan>('/api/routes/plan',{origin_lat:p.coords.latitude,origin_lon:p.coords.longitude,origin_label:'Localização atual',start_local:startLocal,business_keys:remaining,fixed_business_keys:stops.filter(s=>s.fixed).map(s=>s.business_key),excluded_business_keys:[],mode:activeRoute.mode||'driving-car',strategy:activeRoute.strategy||'balanced',available_minutes:activeRoute.available_minutes||240,visit_minutes:activeRoute.visit_minutes||15,max_stops:activeRoute.max_stops||12,return_to_start:false,persist:false});await api.patch(`/api/routes/${activeRoute.id}/stops`,{stops:plan.schedule.map(s=>({business_key:s.business_key,status:'SELECTED',fixed:!!s.fixed,notes:''}))});resolve(plan)}catch(e){reject(e)}},reject,{enableHighAccuracy:true,timeout:8000})}),onSuccess:()=>qc.invalidateQueries({queryKey:['route-street']})})
 const addNearby=useMutation({mutationFn:async()=>{if(!activeRoute?.id||!nearby)return;const current=(activeRoute.stops||[]).filter(s=>!['REMOVED','COMPLETED'].includes(s.status)).map(s=>({business_key:s.business_key,status:s.status||'SELECTED',fixed:!!s.fixed,notes:s.notes||''}));current.splice(Math.min(1,current.length),0,{business_key:nearby.lead.business_key,status:'SELECTED',fixed:false,notes:'Adicionado por proximidade durante a rota'});return api.patch(`/api/routes/${activeRoute.id}/stops`,{stops:current})},onSuccess:()=>qc.invalidateQueries({queryKey:['route-street']})})
 const maps=nextLead?`https://www.google.com/maps/dir/?api=1&destination=${nextLead.lat},${nextLead.lon}`:'#'
 return <div className="mx-auto max-w-3xl space-y-5 pb-24 lg:pb-0"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Prospecção em campo</p><h1 className="mt-1 text-3xl font-bold">Modo rua</h1><p className="mt-1 text-sm text-muted">Próximo destino, registro rápido e ajuste da rota sem voltar ao escritório.</p></div>
  {!navigator.onLine&&<Card className="border-warning/30 bg-warning-soft"><b className="flex items-center gap-2 text-sm text-warning"><CloudOff className="h-4 w-4"/>Modo offline ativo</b><p className="mt-1 text-xs text-muted">A rota continua disponível e as ações são guardadas no dispositivo para sincronizar quando a conexão voltar. Fila atual: {queuedCount}.</p></Card>}
  {!nextLead?<Card><p className="text-sm text-muted">Nenhuma parada disponível.</p><Link to="/routes" className="mt-3 inline-block text-sm font-semibold text-primary">Montar rota</Link></Card>:<>
   <Card className="space-y-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-muted">Próximo destino</p><h2 className="mt-1 text-2xl font-bold">{nextLead.name}</h2><p className="mt-1 text-sm text-muted">{nextLead.address}</p></div><Badge tone="primary">{nextLead.visit_priority_score||0}</Badge></div><p className="text-sm leading-6 text-muted">{nextLead.why_approach}</p>{nextLead.notes&&<div className="rounded-xl border border-warning/20 bg-warning-soft p-3"><b className="text-xs text-warning">Nota antes da visita</b><p className="mt-1 text-sm text-ink">{nextLead.notes}</p></div>}{briefing.data&&<div className="rounded-xl border border-border bg-background p-4"><div className="flex items-center justify-between gap-2"><b className="text-sm">Briefing de 10 segundos</b><Badge tone={briefing.data.intelligence?.conversion_confidence>=70?'success':briefing.data.intelligence?.conversion_confidence>=50?'warning':'neutral'}>confiança {briefing.data.intelligence?.conversion_confidence||0}%</Badge></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div><span className="text-muted">Contato</span><p className="font-semibold">{briefing.data.lead?.decision_maker_name||briefing.data.lead?.contact_name||'Ainda não identificado'}</p></div><div><span className="text-muted">Concorrente / rotina</span><p className="font-semibold">{briefing.data.playbook?.competitor||'Não identificado'}</p></div></div><p className="mt-3 text-sm leading-6"><b>Ângulo sugerido:</b> {briefing.data.playbook?.angle}</p>{briefing.data.last_activities?.[0]&&<p className="mt-2 text-xs text-muted">Última interação: {briefing.data.last_activities[0].details||briefing.data.last_activities[0].activity_type}</p>}{briefing.data.duplicates?.length>0&&<p className="mt-2 rounded-lg bg-warning-soft p-2 text-xs font-semibold text-warning">Atenção: há possível registro duplicado/contato relacionado no CRM.</p>}</div>}{nextStop&&<div className="grid grid-cols-3 gap-2 rounded-xl bg-background p-3 text-center text-xs"><div><b>{nextStop.travel_minutes||0} min</b><span className="block text-muted">deslocamento</span></div><div><b>{nextStop.expected_mrr_value?.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})||'—'}</b><span className="block text-muted">valor esperado</span></div><div><b>{nextStop.fixed?'Sim':'Não'}</b><span className="block text-muted">obrigatório</span></div></div>}<div className="grid gap-2 sm:grid-cols-2"><a href={maps} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-4 font-semibold text-white"><Navigation className="h-4 w-4"/>Abrir rota</a><Button variant="secondary" className="h-12" onClick={()=>arrive.mutate()}><MapPin className="h-4 w-4"/>Cheguei</Button></div></Card>
   {nearby&&<Card className="border-primary/20"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-primary">Oportunidade próxima</p><b className="mt-1 block">{nearby.lead.name}</b><p className="mt-1 text-xs text-muted">A {Math.round(nearby.d)} m desta parada · prioridade {nearby.lead.visit_priority_score||0}</p></div><Button variant="secondary" disabled={addNearby.isPending} onClick={()=>addNearby.mutate()}><Plus className="h-4 w-4"/>Adicionar</Button></div></Card>}
   <Card className="space-y-3"><h2 className="font-semibold">Resultado da visita</h2><select className="h-11 w-full rounded-xl border border-border bg-surface px-3" value={objection} onChange={e=>setObjection(e.target.value)}><option value="">Objeção, se houver</option>{OBJECTIONS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>{objection&&<div className="rounded-xl bg-background p-3 text-sm text-muted"><b className="text-ink">Playbook:</b> {OBJECTION_PLAYBOOK[objection]}</div>}<textarea className="min-h-24 w-full rounded-xl border border-border p-3" placeholder="O que aconteceu? Quem atendeu? Qual o próximo passo?" value={note} onChange={e=>setNote(e.target.value)}/><VoiceNoteButton onText={t=>setNote(n=>`${n}${n?' ':''}${t}`)} label="Falar observação"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{[['VISITED','Visitado'],['NO_OWNER','Responsável ausente'],['INTERESTED','Interessado'],['DEMO','Demo'],['PROPOSAL','Proposta'],['CLIENT','Cliente'],['NOT_INTERESTED','Sem interesse']].map(([v,n])=><Button key={v} variant={v==='CLIENT'?'primary':'secondary'} disabled={quick.isPending} onClick={()=>quick.mutate(v)}>{n}</Button>)}</div></Card>
   {activeRoute?.id&&<div className="grid gap-2 sm:grid-cols-3"><Button variant="secondary" onClick={()=>skip.mutate('SKIPPED')}><SkipForward className="h-4 w-4"/>Pular</Button><Button variant="secondary" onClick={()=>skip.mutate('REMOVED')}><X className="h-4 w-4"/>Remover</Button><Button variant="secondary" disabled={replan.isPending} onClick={()=>replan.mutate()}><RotateCcw className="h-4 w-4"/>{replan.isPending?'Recalculando':'Replanejar restante'}</Button></div>}
  </>}
  <Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Rota atual</h2><p className="mt-1 text-sm text-muted">{activeRoute?.name||'Nenhuma rota salva'}</p></div><Link to="/routes" className="text-sm font-semibold text-primary">Editar rota</Link></div>{activeRoute?.stops&&<div className="mt-4 space-y-2">{activeRoute.stops.slice(0,12).map((s,i)=><div key={s.business_key} className={`flex items-center justify-between rounded-lg border p-2 text-sm ${['COMPLETED'].includes(s.status)?'border-success/30 bg-success-soft':'border-border'}`}><span>{i+1}. {s.name}</span><span className="text-xs text-muted">{s.status}</span></div>)}</div>}</Card>
  {nextLead&&<div className="mobile-action-bar fixed inset-x-0 bottom-0 z-30 grid grid-cols-4 gap-1 border-t border-border bg-surface/95 p-2 backdrop-blur lg:hidden"><a href={nextLead.phone?`tel:${nextLead.phone}`:'#'} className="grid min-h-12 place-items-center rounded-lg text-xs font-semibold text-muted"><Phone className="mb-1 h-4 w-4"/>Ligar</a><a href={maps} target="_blank" rel="noreferrer" className="grid min-h-12 place-items-center rounded-lg text-xs font-semibold text-muted"><Navigation className="mb-1 h-4 w-4"/>Rota</a><button onClick={()=>arrive.mutate()} className="grid min-h-12 place-items-center rounded-lg text-xs font-semibold text-muted"><MapPin className="mb-1 h-4 w-4"/>Cheguei</button><button onClick={()=>quick.mutate('INTERESTED')} className="grid min-h-12 place-items-center rounded-lg bg-primary text-xs font-semibold text-white"><ThumbsUp className="mb-1 h-4 w-4"/>Interessado</button></div>}
 </div>
}
