import {useEffect,useMemo,useState} from 'react'
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query'
import {api} from '@/services/api'
import type {Lead,RoutePlan,RouteStop,SavedRoute} from '@/types'
import {Card} from '@/components/ui/Card'
import {Link} from 'react-router-dom'
import {Badge} from '@/components/ui/Badge'
import {Button} from '@/components/ui/Button'
import {OBJECTIONS,OBJECTION_PLAYBOOK} from '@/lib/options'
import {VoiceNoteButton} from '@/components/productivity/VoiceNoteButton'
import {MapPin,Navigation,SkipForward,X,RotateCcw,Plus} from 'lucide-react'

const CACHE_KEY='beesys_street_route_cache_v1'
const distanceM=(a:[number,number],b:[number,number])=>{const R=6371000,toRad=(v:number)=>v*Math.PI/180;const dLat=toRad(b[0]-a[0]),dLon=toRad(b[1]-a[1]);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a[0]))*Math.cos(toRad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}

export function StreetPage(){
 const qc=useQueryClient()
 const routes=useQuery({queryKey:['routes'],queryFn:()=>api.get<SavedRoute[]>('/api/routes?limit=20')})
 const today=new Date().toISOString().slice(0,10)
 const currentMeta=(routes.data||[]).find(r=>r.route_date===today)||(routes.data||[])[0]
 const route=useQuery({queryKey:['route-street',currentMeta?.id],queryFn:()=>api.get<SavedRoute>(`/api/routes/${currentMeta!.id}`),enabled:!!currentMeta?.id})
 const fallback=useQuery({queryKey:['street-fallback'],queryFn:()=>api.get<Lead[]>('/api/leads?limit=60&min_score=50&visited=no'),enabled:!currentMeta?.id})
 const nearbyPool=useQuery({queryKey:['street-nearby'],queryFn:()=>api.get<Lead[]>('/api/leads?limit=250&min_score=75&visited=no')})
 const[objection,setObjection]=useState(''),[note,setNote]=useState('')
 useEffect(()=>{if(route.data)localStorage.setItem(CACHE_KEY,JSON.stringify(route.data))},[route.data])
 const cached=useMemo(()=>{try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'null') as SavedRoute|null}catch{return null}},[route.data])
 const activeRoute=route.data||(!navigator.onLine?cached:null)
 const stops=(activeRoute?.stops||[]).filter(s=>!['REMOVED','COMPLETED','SKIPPED'].includes(s.status))
 const nextStop=stops[0]
 const nextLead=nextStop?({business_key:nextStop.business_key,name:nextStop.name,address:nextStop.address,lat:nextStop.lat,lon:nextStop.lon,visit_priority_score:nextStop.visit_priority_score,why_approach:nextStop.why_approach,pipeline_status:nextStop.pipeline_status,notes:nextStop.lead_notes,assigned_to:nextStop.assigned_to,campaign_name:nextStop.campaign_name} as Lead):(fallback.data||[])[0]
 const routeKeys=new Set((activeRoute?.stops||[]).map(s=>s.business_key))
 const nearby=useMemo(()=>{if(!nextLead)return null;return (nearbyPool.data||[]).filter(l=>!routeKeys.has(l.business_key)&&!l.is_large_chain&&!l.do_not_contact).map(l=>({lead:l,d:distanceM([nextLead.lat,nextLead.lon],[l.lat,l.lon])})).filter(x=>x.d<=450).sort((a,b)=>(b.lead.visit_priority_score||0)-(a.lead.visit_priority_score||0)||a.d-b.d)[0]||null},[nearbyPool.data,nextLead?.business_key,activeRoute?.id])
 const quick=useMutation({mutationFn:(outcome:string)=>{if(!nextLead)throw new Error('Sem próximo lead');const found=OBJECTIONS.find(x=>x[0]===objection);return api.post(`/api/leads/${encodeURIComponent(nextLead.business_key)}/outcomes`,{outcome,notes:note,objection_code:found?.[0],objection_label:found?.[1],objection_details:note})},onSuccess:async()=>{if(activeRoute?.id&&nextLead)await api.patch(`/api/routes/${activeRoute.id}/stops/${encodeURIComponent(nextLead.business_key)}`,{status:'COMPLETED',reason:''});setNote('');setObjection('');qc.invalidateQueries({queryKey:['route-street']});qc.invalidateQueries({queryKey:['street-fallback']});qc.invalidateQueries({queryKey:['street-nearby']})}})
 const arrive=useMutation({mutationFn:()=>new Promise<any>((resolve,reject)=>{if(!nextLead)return reject(new Error('Sem lead'));navigator.geolocation.getCurrentPosition(p=>api.post(`/api/leads/${encodeURIComponent(nextLead.business_key)}/activities`,{activity_type:'ARRIVED',details:'Check-in pelo Modo Rua',outcome:'ARRIVED',lat:p.coords.latitude,lon:p.coords.longitude}).then(resolve).catch(reject),reject,{enableHighAccuracy:true,timeout:8000})})})
 const skip=useMutation({mutationFn:(status:'SKIPPED'|'REMOVED')=>activeRoute&&nextLead?api.patch(`/api/routes/${activeRoute.id}/stops/${encodeURIComponent(nextLead.business_key)}`,{status,reason:status==='SKIPPED'?'Pulado durante a rota':'Removido da rota no modo rua'}):Promise.resolve({}),onSuccess:()=>qc.invalidateQueries({queryKey:['route-street']})})
 const replan=useMutation({mutationFn:()=>new Promise<any>((resolve,reject)=>{if(!activeRoute?.id||!stops.length)return reject(new Error('Sem rota ativa'));navigator.geolocation.getCurrentPosition(async p=>{try{const remaining=stops.map(s=>s.business_key);const plan=await api.post<RoutePlan>('/api/routes/plan',{origin_lat:p.coords.latitude,origin_lon:p.coords.longitude,origin_label:'Localização atual',business_keys:remaining,fixed_business_keys:stops.filter(s=>s.fixed).map(s=>s.business_key),excluded_business_keys:[],mode:activeRoute.mode||'driving-car',strategy:activeRoute.strategy||'balanced',available_minutes:activeRoute.available_minutes||240,visit_minutes:activeRoute.visit_minutes||15,max_stops:activeRoute.max_stops||12,return_to_start:false,persist:false});await api.patch(`/api/routes/${activeRoute.id}/stops`,{stops:plan.schedule.map(s=>({business_key:s.business_key,status:'SELECTED',fixed:!!s.fixed,notes:''}))});resolve(plan)}catch(e){reject(e)}},reject,{enableHighAccuracy:true,timeout:8000})}),onSuccess:()=>qc.invalidateQueries({queryKey:['route-street']})})
 const addNearby=useMutation({mutationFn:async()=>{if(!activeRoute?.id||!nearby)return;const current=(activeRoute.stops||[]).filter(s=>!['REMOVED','COMPLETED'].includes(s.status)).map(s=>({business_key:s.business_key,status:s.status||'SELECTED',fixed:!!s.fixed,notes:s.notes||''}));current.splice(Math.min(1,current.length),0,{business_key:nearby.lead.business_key,status:'SELECTED',fixed:false,notes:'Adicionado por proximidade durante a rota'});return api.patch(`/api/routes/${activeRoute.id}/stops`,{stops:current})},onSuccess:()=>qc.invalidateQueries({queryKey:['route-street']})})
 const maps=nextLead?`https://www.google.com/maps/dir/?api=1&destination=${nextLead.lat},${nextLead.lon}`:'#'
 return <div className="mx-auto max-w-3xl space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Prospecção em campo</p><h1 className="mt-1 text-3xl font-bold">Modo rua</h1><p className="mt-1 text-sm text-muted">Próximo destino, registro rápido e ajuste da rota sem voltar ao escritório.</p></div>
  {!navigator.onLine&&<Card className="border-warning/30 bg-warning-soft"><b className="text-sm text-warning">Modo offline parcial</b><p className="mt-1 text-xs text-muted">A rota salva continua disponível para consulta. Alterações no CRM precisam de conexão.</p></Card>}
  {!nextLead?<Card><p className="text-sm text-muted">Nenhuma parada disponível.</p><Link to="/routes" className="mt-3 inline-block text-sm font-semibold text-primary">Montar rota</Link></Card>:<>
   <Card className="space-y-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-muted">Próximo destino</p><h2 className="mt-1 text-2xl font-bold">{nextLead.name}</h2><p className="mt-1 text-sm text-muted">{nextLead.address}</p></div><Badge tone="primary">{nextLead.visit_priority_score||0}</Badge></div><p className="text-sm leading-6 text-muted">{nextLead.why_approach}</p>{nextLead.notes&&<div className="rounded-xl border border-warning/20 bg-warning-soft p-3"><b className="text-xs text-warning">Nota antes da visita</b><p className="mt-1 text-sm text-ink">{nextLead.notes}</p></div>}{nextStop&&<div className="grid grid-cols-3 gap-2 rounded-xl bg-background p-3 text-center text-xs"><div><b>{nextStop.travel_minutes||0} min</b><span className="block text-muted">deslocamento</span></div><div><b>{nextStop.expected_mrr_value?.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})||'—'}</b><span className="block text-muted">valor esperado</span></div><div><b>{nextStop.fixed?'Sim':'Não'}</b><span className="block text-muted">obrigatório</span></div></div>}<div className="grid gap-2 sm:grid-cols-2"><a href={maps} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-4 font-semibold text-white"><Navigation className="h-4 w-4"/>Abrir rota</a><Button variant="secondary" className="h-12" onClick={()=>arrive.mutate()}><MapPin className="h-4 w-4"/>Cheguei</Button></div></Card>
   {nearby&&<Card className="border-primary/20"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-primary">Oportunidade próxima</p><b className="mt-1 block">{nearby.lead.name}</b><p className="mt-1 text-xs text-muted">A {Math.round(nearby.d)} m desta parada · prioridade {nearby.lead.visit_priority_score||0}</p></div><Button variant="secondary" disabled={addNearby.isPending} onClick={()=>addNearby.mutate()}><Plus className="h-4 w-4"/>Adicionar</Button></div></Card>}
   <Card className="space-y-3"><h2 className="font-semibold">Resultado da visita</h2><select className="h-11 w-full rounded-xl border border-border bg-surface px-3" value={objection} onChange={e=>setObjection(e.target.value)}><option value="">Objeção, se houver</option>{OBJECTIONS.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>{objection&&<div className="rounded-xl bg-background p-3 text-sm text-muted"><b className="text-ink">Playbook:</b> {OBJECTION_PLAYBOOK[objection]}</div>}<textarea className="min-h-24 w-full rounded-xl border border-border p-3" placeholder="O que aconteceu? Quem atendeu? Qual o próximo passo?" value={note} onChange={e=>setNote(e.target.value)}/><VoiceNoteButton onText={t=>setNote(n=>`${n}${n?' ':''}${t}`)} label="Falar observação"/><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{[['VISITED','Visitado'],['NO_OWNER','Responsável ausente'],['INTERESTED','Interessado'],['DEMO','Demo'],['PROPOSAL','Proposta'],['CLIENT','Cliente'],['NOT_INTERESTED','Sem interesse']].map(([v,n])=><Button key={v} variant={v==='CLIENT'?'primary':'secondary'} disabled={quick.isPending} onClick={()=>quick.mutate(v)}>{n}</Button>)}</div></Card>
   {activeRoute?.id&&<div className="grid gap-2 sm:grid-cols-3"><Button variant="secondary" onClick={()=>skip.mutate('SKIPPED')}><SkipForward className="h-4 w-4"/>Pular</Button><Button variant="secondary" onClick={()=>skip.mutate('REMOVED')}><X className="h-4 w-4"/>Remover</Button><Button variant="secondary" disabled={replan.isPending} onClick={()=>replan.mutate()}><RotateCcw className="h-4 w-4"/>{replan.isPending?'Recalculando':'Replanejar restante'}</Button></div>}
  </>}
  <Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Rota atual</h2><p className="mt-1 text-sm text-muted">{activeRoute?.name||'Nenhuma rota salva'}</p></div><Link to="/routes" className="text-sm font-semibold text-primary">Editar rota</Link></div>{activeRoute?.stops&&<div className="mt-4 space-y-2">{activeRoute.stops.slice(0,12).map((s,i)=><div key={s.business_key} className={`flex items-center justify-between rounded-lg border p-2 text-sm ${['COMPLETED'].includes(s.status)?'border-success/30 bg-success-soft':'border-border'}`}><span>{i+1}. {s.name}</span><span className="text-xs text-muted">{s.status}</span></div>)}</div>}</Card>
 </div>
}
