import {useQuery} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {api} from '@/services/api'
import type {TodayWorkspace} from '@/types'
import {Card} from '@/components/ui/Card'
import {Badge} from '@/components/ui/Badge'
import {CalendarClock,MapPinned,Target,ArrowRight} from 'lucide-react'

export function TodayPage(){
 const q=useQuery({queryKey:['today'],queryFn:()=>api.get<TodayWorkspace>('/api/today'),refetchInterval:60000});const d=q.data
 if(!d)return <p className="text-sm text-muted">Carregando o plano de hoje...</p>
 return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Operação comercial</p><h1 className="mt-1 text-3xl font-bold">Hoje</h1><p className="mt-1 text-sm text-muted">O que merece sua atenção primeiro, sem precisar procurar em várias telas.</p></div>
  <div className="grid gap-4 md:grid-cols-3"><Card><div className="flex items-center gap-2 text-muted"><CalendarClock className="h-4 w-4"/><span className="text-sm">Follow-ups vencendo</span></div><p className="mt-2 text-3xl font-bold">{d.due_followups.length}</p></Card><Card><div className="flex items-center gap-2 text-muted"><MapPinned className="h-4 w-4"/><span className="text-sm">Rotas de hoje</span></div><p className="mt-2 text-3xl font-bold">{d.routes.length}</p></Card><Card><div className="flex items-center gap-2 text-muted"><Target className="h-4 w-4"/><span className="text-sm">Metas ativas</span></div><p className="mt-2 text-3xl font-bold">{d.goals.length}</p></Card></div>
  <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Próximas melhores ações</h2><p className="mt-1 text-sm text-muted">Priorizadas por etapa comercial, score e urgência.</p></div><Link to="/leads" className="text-sm font-semibold text-primary">Abrir CRM</Link></div><div className="mt-4 space-y-3">{d.next_actions.slice(0,12).map(({lead,action})=><Link key={lead.business_key} to={`/leads/${encodeURIComponent(lead.business_key)}`} className="block rounded-xl border border-border p-4 hover:bg-surface-hover"><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{lead.name}</b><p className="mt-1 text-xs text-muted">{lead.address}</p></div><Badge tone={action.priority>=85?'primary':action.priority>=60?'warning':'neutral'}>{action.label}</Badge></div><p className="mt-2 text-sm text-muted">{action.reason}</p><div className="mt-3 flex items-center justify-between text-xs"><span className="text-muted">Prioridade {lead.visit_priority_score||0} · {lead.aging_label}</span><ArrowRight className="h-4 w-4 text-primary"/></div></Link>)}{!d.next_actions.length&&<p className="text-sm text-muted">Nenhuma ação prioritária agora.</p>}</div></Card>
   <div className="space-y-5"><Card><h2 className="font-semibold">Follow-ups</h2><div className="mt-4 space-y-3">{d.due_followups.slice(0,8).map(f=><Link key={f.id} to={`/leads/${encodeURIComponent(f.business_key)}`} className="block rounded-xl border border-border p-3"><b className="text-sm">{f.business_name||f.title}</b><p className="mt-1 text-xs text-muted">{f.title} · {new Date(f.due_at).toLocaleString('pt-BR')}</p></Link>)}{!d.due_followups.length&&<p className="text-sm text-muted">Sem retornos vencidos.</p>}</div></Card>
    <Card><h2 className="font-semibold">Metas</h2><div className="mt-4 space-y-4">{d.goals.map(g=>{const pct=Math.min(100,100*Number(g.progress||0)/Math.max(1,Number(g.target||1)));return <div key={g.id}><div className="flex justify-between text-sm"><span>{g.label||g.metric}</span><b>{Number(g.progress||0).toFixed(g.metric==='MRR'?2:0)} / {g.target}</b></div><div className="mt-2 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:`${pct}%`}}/></div></div>})}{!d.goals.length&&<p className="text-sm text-muted">Nenhuma meta ativa hoje.</p>}</div></Card>
   </div></div>
 </div>
}
