import {useQuery} from '@tanstack/react-query'
import {Link} from 'react-router-dom'
import {api} from '@/services/api'
import type {TodayWorkspace} from '@/types'
import {Card} from '@/components/ui/Card'
import {Badge} from '@/components/ui/Badge'
import {CalendarClock,MapPinned,Target,ArrowRight,Flame,AlertTriangle,Route,Clock3} from 'lucide-react'
import {PageSkeleton} from '@/components/ui/Skeleton'

const goalProjection=(g:any)=>{const progress=Number(g.progress||0),target=Number(g.target||0);if(progress>=target)return 'Meta atingida';const start=new Date(g.start_at||Date.now()),end=new Date(g.end_at||Date.now());const elapsed=Math.max(1,Date.now()-start.getTime()),total=Math.max(elapsed,end.getTime()-start.getTime());const projected=progress*total/elapsed;if(projected>=target)return 'No ritmo atual, a meta tende a ser atingida';return `Projeção atual: ${Math.round(projected)} de ${target}`}

export function TodayPage(){
 const q=useQuery({queryKey:['today'],queryFn:()=>api.get<TodayWorkspace>('/api/today'),refetchInterval:60000});const d=q.data
 if(!d)return <PageSkeleton/>
 const hot=d.next_actions.filter(x=>(x.lead.visit_priority_score||0)>=80&&['VISIT','CONTACT'].includes(x.action.action)).slice(0,5)
 const stale=d.next_actions.filter(x=>(x.lead.aging_days||0)>=30).slice(0,5)
 const route=d.routes[0]
 return <div className="space-y-7"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">Operação comercial</p><h1 className="mt-1 text-3xl font-bold">Hoje</h1><p className="mt-1 text-sm text-muted">Sua fila de trabalho: rota, retornos, metas e oportunidades que não deveriam esperar.</p></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><div className="flex items-center gap-2 text-muted"><CalendarClock className="h-4 w-4"/><span className="text-sm">Follow-ups vencendo</span></div><p className="metric-number mt-2 text-3xl font-bold">{d.due_followups.length}</p><Link className="mt-2 inline-block text-xs font-semibold text-primary" to="/followups">Abrir retornos</Link></Card><Card><div className="flex items-center gap-2 text-muted"><Route className="h-4 w-4"/><span className="text-sm">Rota de hoje</span></div><p className="metric-number mt-2 text-3xl font-bold">{d.routes.length?`${d.routes.length}`:'—'}</p><p className="mt-2 text-xs text-muted">{route?.name||'Nenhuma rota salva para hoje'}</p></Card><Card><div className="flex items-center gap-2 text-muted"><Flame className="h-4 w-4"/><span className="text-sm">Leads quentes</span></div><p className="metric-number mt-2 text-3xl font-bold">{hot.length}</p><p className="mt-2 text-xs text-muted">Prioridade 80+ com ação recomendada</p></Card><Card><div className="flex items-center gap-2 text-muted"><Target className="h-4 w-4"/><span className="text-sm">Metas ativas</span></div><p className="metric-number mt-2 text-3xl font-bold">{d.goals.length}</p><Link className="mt-2 inline-block text-xs font-semibold text-primary" to="/goals">Acompanhar metas</Link></Card></div>
  {route&&<Card className="border-primary/20 bg-primary-soft/50"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">Rota preparada</p><h2 className="mt-1 font-semibold">{route.name}</h2><p className="mt-1 text-sm text-muted">{route.mode==='foot-walking'?'A pé':'Carro'} · até {route.max_stops} paradas · {route.available_minutes} min disponíveis</p></div><Link to="/street" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Iniciar modo rua <ArrowRight className="h-4 w-4"/></Link></div></Card>}
  <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Próximas melhores ações</h2><p className="mt-1 text-sm text-muted">Priorizadas por etapa comercial, score e urgência.</p></div><Link to="/leads" className="text-sm font-semibold text-primary">Abrir CRM</Link></div><div className="mt-4 divide-y divide-border">{d.next_actions.slice(0,10).map(({lead,action})=><Link key={lead.business_key} to={`/leads/${encodeURIComponent(lead.business_key)}`} className="block py-4 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><b>{lead.name}</b><p className="mt-1 line-clamp-1 text-xs text-muted">{lead.address}</p></div><Badge tone={action.priority>=85?'primary':action.priority>=60?'warning':'neutral'}>{action.label}</Badge></div><p className="mt-2 text-sm text-muted">{action.reason}</p><div className="mt-2 flex items-center justify-between text-xs"><span className="text-muted">Prioridade {lead.visit_priority_score||0} · {lead.aging_label}</span><ArrowRight className="h-4 w-4 text-primary"/></div></Link>)}{!d.next_actions.length&&<p className="text-sm text-muted">Nenhuma ação prioritária agora.</p>}</div></Card>
   <div className="space-y-5"><Card><h2 className="font-semibold">Follow-ups</h2><div className="mt-4 space-y-3">{d.due_followups.slice(0,6).map(f=><Link key={f.id} to={`/leads/${encodeURIComponent(f.business_key)}`} className="block rounded-xl border border-border p-3"><b className="text-sm">{f.business_name||f.title}</b><p className="mt-1 text-xs text-muted">{f.title} · {new Date(f.due_at).toLocaleString('pt-BR')}</p></Link>)}{!d.due_followups.length&&<p className="text-sm text-muted">Sem retornos vencidos.</p>}</div></Card>
    <Card><h2 className="font-semibold">Ritmo das metas</h2><div className="mt-4 space-y-5">{d.goals.map(g=>{const value=Number(g.progress||0),target=Number(g.target||1),pct=Math.min(100,100*value/Math.max(1,target));return <div key={g.id}><div className="flex justify-between gap-3 text-sm"><span>{g.label||g.metric}</span><b>{value.toFixed(g.metric==='MRR'?2:0)} / {target}</b></div><div className="mt-2 h-2 rounded-full bg-background"><div className="h-full rounded-full bg-primary" style={{width:`${pct}%`}}/></div><p className="mt-1 text-xs text-muted">{goalProjection(g)}</p></div>})}{!d.goals.length&&<p className="text-sm text-muted">Nenhuma meta ativa hoje.</p>}</div></Card></div></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card><div className="flex items-center gap-2"><Flame className="h-4 w-4 text-danger"/><h2 className="font-semibold">Leads quentes para atacar</h2></div><div className="mt-4 space-y-2">{hot.map(({lead})=><Link key={lead.business_key} to={`/leads/${encodeURIComponent(lead.business_key)}`} className="flex items-center justify-between gap-3 rounded-xl border border-border p-3"><div><b className="text-sm">{lead.name}</b><p className="mt-1 text-xs text-muted">{lead.why_approach}</p></div><span className="text-lg font-bold text-danger">{lead.visit_priority_score}</span></Link>)}{!hot.length&&<p className="text-sm text-muted">Nenhum lead de prioridade 80+ pendente.</p>}</div></Card><Card><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-warning"/><h2 className="font-semibold">Leads esfriando</h2></div><p className="mt-1 text-sm text-muted">Oportunidades com 30+ dias sem avanço merecem decisão: retomar ou encerrar.</p><div className="mt-4 space-y-2">{stale.map(({lead})=><Link key={lead.business_key} to={`/leads/${encodeURIComponent(lead.business_key)}`} className="flex items-center justify-between rounded-xl border border-border p-3"><div><b className="text-sm">{lead.name}</b><p className="text-xs text-muted">{lead.aging_label} · {lead.pipeline_status||'NEW'}</p></div><Clock3 className="h-4 w-4 text-warning"/></Link>)}{!stale.length&&<p className="text-sm text-muted">Nenhum lead parado por 30+ dias.</p>}</div></Card></div>
 </div>
}
